### ISSUE TITLE
Development setup is broken - No such file or directory: 'curl-config'

### ISSUE THREAD

**Issue by abitrolly** [pypa/warehouse#10446]
`make build` on `main` gives this currently and fails
```
...
Installing collected packages: pyflakes, pycodestyle, mccabe, pbr, flake8, typing-extensions, toml, stevedore, restructuredtext-lint, regex, platformdirs, pathspec, parsy, mypy-extensions, flake8-polyfill, attrs, pep8-naming, isort, doc8, curlylint, black
Successfully installed attrs-21.2.0 black-21.11b1 curlylint-0.13.0 doc8-0.10.1 flake8-4.0.1 flake8-polyfill-1.0.2 isort-5.10.1 mccabe-0.6.1 mypy-extensions-0.4.3 parsy-1.1.0 pathspec-0.9.0 pbr-5.7.0 pep8-naming-0.12.1 platformdirs-2.4.0 pycodestyle-2.8.0 pyflakes-2.4.0 regex-2021.11.10 restructuredtext-lint-1.3.2 stevedore-3.5.0 toml-0.10.2 typing-extensions-3.10.0.2
# install ipython if enabled
/home/runner/work/warehouse/warehouse/.state/env/bin/pip-compile --allow-unsafe --generate-hashes --output-file=requirements/main.txt requirements/main.in
    ERROR: Command errored out with exit status 1:
     command: /home/runner/work/warehouse/warehouse/.state/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-7hbghyfu/pycurl/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-7hbghyfu/pycurl/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mqfu4yi0
         cwd: /tmp/pip-resolver-7hbghyfu/pycurl/
    Complete output (22 lines):
    Traceback (most recent call last):
      File "/tmp/pip-resolver-7hbghyfu/pycurl/setup.py", line 234, in configure_unix
        p = subprocess.Popen((self.curl_config(), '--version'),
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config'
```

**Additional context**

* Revealed by #10052

**Comment by di** [comment]
This is specific to your changes in #10052 but ultimately  due to https://github.com/pypa/warehouse/issues/10447: it's trying to `make .state/env/pyvenv.cfg` (which is unnecessary) and the host in your action is missing some necessary platform libraries for installing `pycurl`.

Closing this in favor of #10447 as it more accurately describes the actual issue.

**Comment by abitrolly** [comment]
It is not specific to my changes. My changes merely invoke `make serve` much like everybody who follow official docs do to start with development.

**Comment by abitrolly** [comment]
It would be more convenient to track issues in this tracker if they would kept open until the original problem described by OP is indeed fixed, even if the solution discussed and implemented in other issues.
