### ISSUE TITLE
pypi.python.org returns [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by isatyawanj** [pypa/warehouse#10523]
**Environment**
OS: RHEL 7.9
Python 2.7.5 (default, Aug 13 2020, 02:51:10) and **Python 3.6.8 (default, Aug 13 2020, 07:46:32)**
OpenSSL 1.0.2k-fips  26 Jan 2017

**Problem description:** 

My pyenv build is failing due to the following error:

```
   1 location(s) to search for versions of pip:
  * https://pypi.python.org/simple/pip/
  Getting page https://pypi.python.org/simple/pip/
  Looking up "https://pypi.python.org/simple/pip/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  Incremented Retry for (url='/simple/pip/'): Retry(total=4, connect=None, read=None, redirect=None)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /simple/pip/
  Starting new HTTPS connection (2): pypi.python.org
  Incremented Retry for (url='/simple/pip/'): Retry(total=3, connect=None, read=None, redirect=None)
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /simple/pip/
  Starting new HTTPS connection (3): pypi.python.org
  Incremented Retry for (url='/simple/pip/'): Retry(total=2, connect=None, read=None, redirect=None)
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /simple/pip/
  Starting new HTTPS connection (4): pypi.python.org
  Incremented Retry for (url='/simple/pip/'): Retry(total=1, connect=None, read=None, redirect=None)
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /simple/pip/
  Starting new HTTPS connection (5): pypi.python.org
  Incremented Retry for (url='/simple/pip/'): Retry(total=0, connect=None, read=None, redirect=None)
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /simple/pip/
  Starting new HTTPS connection (6): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/pip/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))) - skipping
  Could not find a version that satisfies the requirement pip===18.1 (from -c tools/pyenv-infra.upper-constraints.txt (line 1)) (from versions: )
Cleaning up...
No matching distribution found for pip===18.1 (from -c tools/pyenv-infra.upper-constraints.txt (line 1))
Exception information:
Traceback (most recent call last):
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for pip===18.1 (from -c tools/pyenv-infra.upper-constraints.txt (line 1))
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/utils/outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 510, in get
    return self.request('GET', url, **kwargs)
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 497, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/opt/oiaas-deployment-ansible/pyenv-ansible-2.9/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/pip/json (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')))

```
**Troubleshooting steps**

1. Ping and DNS resolution is good and I can reach server on 443:
```
[xxx - root@xxx]# ping pypi.python.org
PING dualstack.python.map.fastly.net (151.101.120.223) 56(84) bytes of data.
64 bytes from 151.101.120.223 (151.101.120.223): icmp_seq=1 ttl=46 time=257 ms
64 bytes from 151.101.120.223 (151.101.120.223): icmp_seq=2 ttl=46 time=256 ms

[xxx] root@xxx:~# dig pypi.python.org

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> pypi.python.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63185
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pypi.python.org.		IN	A

;; ANSWER SECTION:
pypi.python.org.	31036	IN	CNAME	dualstack.python.map.fastly.net.
dualstack.python.map.fastly.net. 30 IN	A	151.101.120.223

;; AUTHORITY SECTION:
fastly.net.		3075	IN	NS	ns1.fastly.net.
fastly.net.		3075	IN	NS	ns2.fastly.net.
fastly.net.		3075	IN	NS	ns4.fastly.net.
fastly.net.		3075	IN	NS	ns3.fastly.net.

;; ADDITIONAL SECTION:
ns2.fastly.net.		833	IN	A	104.156.80.32
ns4.fastly.net.		833	IN	A	104.156.84.32
ns3.fastly.net.		3076	IN	A	23.235.36.32
ns1.fastly.net.		3172	IN	A	23.235.32.32

;; Query time: 174 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun Dec 26 07:23:01 UTC 2021
;; MSG SIZE  rcvd: 241


[xxx] root@xxx:~# telnet pypi.python.org 443
Trying 151.101.120.223...
Connected to pypi.python.org.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
```

2. Redhat provides a simple article to troubleshoot such issues => https://access.redhat.com/articles/2039753. I am running a simple request via a python script: 
```
cat urllib2-test.py
#!/usr/bin/env python
try:   
    import urllib2 #python2
except:
    import urllib.request as urllib2 #python3
import sys
req = urllib2.Request(sys.argv[1], headers={'User-Agent':'Mozilla/5.0'})
urllib2.urlopen(req)
```
and here are the results: 
```
#python urllib2-test.py https://pypi.python.org
Traceback (most recent call last):
  File "urllib2-test.py", line 10, in <module>
    urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
```
I tried both `python` and `python3`, results are the same. Note that if I use any other URL, the request completes without any error, for ex. `python urllib2-test.py https://google.com`. 

3. **pyenv build is getting successfully created if I use another package repository**, for ex:
```
pip install **--index-url https://mirrors.sustech.edu.cn/pypi/simple** -r requirements.txt -c upper-constraints.txt --upgrade
```
This means that pypi.python.org is resetting the connection and there seems very little probability of a network configuration issue. 

4. I tried disabling IPv6 as well and that's also doesn't make any difference. 

5. Another interesting fact is that it works well for my servers in France but not for my servers in India and Singapore.  This is strange and it could be due to some CDN-related issue but I have the reason to not suspect local or ISP network configuration because of point (3) above. 

Also, everything was working 1 week back and the issue was intermittent but now it fails each time. No network configuration change happened in between.

It seems something is wrong with the pypi.python.org repository and the connection is being reset. 
Let me know if any further information is needed.  Thanks for helping me with this issue !!!

**Comment by isatyawanj** [comment]
I found an **exactly** similar issue https://github.com/pypa/warehouse/issues/4779 which claims that removing pip cache solved the issue, but I have already tried it, and didn't solve this for me.
