### ISSUE TITLE
auto-py-to-exe  ImportError

### ISSUE THREAD

**Issue by Envases** [pypa/warehouse#11409]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

Good afternoon,

I have recently tried to install auto-py-to-exe and had no errors at this step. The problem comes when I try to run the code. I get an error as follows:

ImportError: cannot import name 'chrome' from 'eel'

Complete Trace Log

C:\>auto-py-to-exe
Traceback (most recent call last):
  File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\Scripts\auto-py-to-exe.exe\__main__.py", line 4, in <module>
  File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_py_to_exe\__main__.py", line 10, in <module>
    from . import ui
  File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_py_to_exe\ui.py", line 8, in <module>
    from . import utils
  File "C:\Users\ANaberan\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_py_to_exe\utils.py", line 8, in <module>
    from eel import chrome
ImportError: cannot import name 'chrome' from 'eel' (unknown location)

C:\>

Regards and great work

**Comment by Envases** [comment]
Thanks, I will have a look into it and check out if any solution.
