### ISSUE TITLE
PyPI Artist demo code does not work

### ISSUE THREAD

**Issue by nicolad76** [pypa/warehouse#11598]
Hi,
I am evaluating PyPI and I went through the demo at this page https://pypi.org/project/shazamio/
I tested "recognize track" code and it worked like a charm. 
I noticed that the output does not include the name of the artist but only ids.
The json for artist is:
 'artists': [{
                'id': '42',
                'adamid': '4488522'
            }
        ],

If I use either 42 or 4488522 in the artist info demo code, I get the following error:

C:\Development\python\test2.py:14: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "C:\Users\nicola\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\shazamio\utils.py", line 17, in validate_json
    return await resp.json(content_type=content_type)
  File "C:\Users\nicola\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.shazam.com/discovery/v3/en/GB/web/artist/4488522?shazamapiversion=v3&video=v3+')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Development\python\test2.py", line 15, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Development\python\test2.py", line 8, in main
    about_artist = await shazam.artist_about(artist_id)
  File "C:\Users\nicola\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\shazamio\api.py", line 50, in artist_about
    return await self.request(
  File "C:\Users\nicola\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\shazamio\client.py", line 14, in request
    return await validate_json(resp, *args)
  File "C:\Users\nicola\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\shazamio\utils.py", line 20, in validate_json
    raise FailedDecodeJson(f"Check args, URL is invalid\nURL- {bad_url}")
shazamio.exceptions.FailedDecodeJson: Check args, URL is invalid
URL- https://www.shazam.com/discovery/v3/en/GB/web/artist/4488522?shazamapiversion=v3&video=v3+

Am I doing something wrong?
Thanks
Nicola

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
