### ISSUE TITLE
`make serve` ends in an error

### ISSUE THREAD

**Issue by karan** [pypa/warehouse#1217]
I was trying to setup warehouse for local dev but after running `make serve` for over an hour, it failed with the following trace:

```
Collecting hiredis==0.2.0 (from -r requirements/main.txt (line 51))
  Downloading hiredis-0.2.0.tar.gz (46kB)
Collecting redis==2.10.5 (from -r requirements/main.txt (line 53))
  Downloading redis-2.10.5-py2.py3-none-any.whl (60kB)
Collecting html5lib==0.9999999 (from -r requirements/main.txt (line 56))
  Downloading html5lib-0.9999999.tar.gz (889kB)
Collecting itsdangerous==0.24 (from -r requirements/main.txt (line 58))
  Downloading itsdangerous-0.24.tar.gz (46kB)
Collecting Jinja2==2.8 (from -r requirements/main.txt (line 60))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 228, in _error_catcher
    yield
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 310, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 49, in read
    data = self.__fp.read(amt)
  File "/usr/local/lib/python3.5/http/client.py", line 433, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.5/http/client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.5/ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.5/ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.5/ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python3.5/site-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python3.5/site-packages/pip/download.py", line 649, in unpack_http_url
    hashes)
  File "/usr/local/lib/python3.5/site-packages/pip/download.py", line 871, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/local/lib/python3.5/site-packages/pip/download.py", line 595, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python3.5/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python3.5/site-packages/pip/download.py", line 563, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python3.5/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/local/lib/python3.5/site-packages/pip/download.py", line 552, in resp_read
    decode_content=False):
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 353, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 320, in read
    flush_decoder = True
  File "/usr/local/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 233, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.
ERROR: Service 'static' failed to build: The command '/bin/sh -c set -x     && apt-get update     && apt-get install inotify-tools wget bzip2 gcc g++ make libpq-dev libjpeg-dev libffi-dev --no-install-recommends -y     && rm -rf node_modules     && wget https://saucelabs.com/downloads/sc-4.3.14-linux.tar.gz -O /tmp/sc.tar.gz     && tar zxvf /tmp/sc.tar.gz --strip 1 -C /usr/     && chmod 755 /usr/bin/sc     && npm install -g phantomjs-prebuilt gulp-cli     && npm install     && pip install -U pip setuptools     && pip install -r requirements/dev.txt                    -r requirements/tests.txt     && pip install -r requirements/deploy.txt                    -r requirements/main.txt     && find /usr/local -type f -name '*.pyc' -name '*.pyo' -delete     && rm -rf ~/.cache/     && apt-get purge bzip2 gcc g++ make libpq-dev libffi-dev -y     && apt-get autoremove -y     && apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 2
make: *** [.state/docker-build] Error 1
```

Pretty annoying since it took quite a while to get there, and the error doesn't seem very helpful either.

Is there a more reliable and faster way to setup the dev env?

**Comment by dstufft** [comment]
That looks like you had a timeout error when pip was attempting to install from PyPI. We don't have anything in place that doesn't invoke pip to install from PyPI though, so the best bet is to just re-run it.

**Comment by karan** [comment]
Ah running again worked.
