### ISSUE TITLE
Search on dev gives index_not_found_exception

### ISSUE THREAD

**Issue by karan** [pypa/warehouse#1227]
`http://192.168.99.100/search/?q=finance` gives:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/app/warehouse/raven.py", line 41, in raven_tween
    return handler(request)
  File "/usr/local/lib/python3.5/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/usr/local/lib/python3.5/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/usr/local/lib/python3.5/site-packages/pyramid_tm/compat.py", line 15, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/app/warehouse/cache/http.py", line 69, in conditional_http_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/usr/local/lib/python3.5/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/app/warehouse/sessions.py", line 291, in wrapped
    return view(context, request)
  File "/app/warehouse/csrf.py", line 38, in wrapped
    return view(context, request)
  File "/usr/local/lib/python3.5/site-packages/pyramid/viewderivers.py", line 512, in csrf_view
    return view(context, request)
  File "/app/warehouse/cache/origin/__init__.py", line 81, in wrapped
    return view(context, request)
  File "/usr/local/lib/python3.5/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.5/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/app/warehouse/views.py", line 199, in search
    url_maker=paginate_url_factory(request),
  File "/app/warehouse/utils/paginate.py", line 62, in ElasticsearchPage
    return Page(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/paginate/__init__.py", line 251, in __init__
    self.items = list(self.collection[first:last])
  File "/app/warehouse/utils/paginate.py", line 44, in __getitem__
    self.results = self.query[range].execute()
  File "/usr/local/lib/python3.5/site-packages/elasticsearch_dsl/search.py", line 579, in execute
    **self._params
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 548, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')
```

I've done `make build` and `make serve`. Maybe `make initdb` file should index the db as well?

**Comment by dstufft** [comment]
Hmm, ``make initdb`` is supposed to index it, it's strange that it didn't for you.

**Comment by karan** [comment]
Rerunning `make initdb` worked! Closing.
