### ISSUE TITLE
Zip file in repository cannot be unzipped after download

### ISSUE THREAD

**Issue by fullautodotcom** [pypa/warehouse#1401]
```
$ wget  https://pypi.io/packages/source/s/setuptools/setuptools-24.3.0.zip

$ unzip setuptools-24.3.0.zip
Archive:  setuptools-24.3.0.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of setuptools-24.3.0.zip or
        setuptools-24.3.0.zip.zip, and cannot find setuptools-24.3.0.zip.ZIP, period.
```

Discovered when trying to install ez_install.py

```
$ python ez_setup.py
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-24.3.0.zip
Extracting in /tmp/tmp3SCjO0
Traceback (most recent call last):
  File "ez_setup.py", line 426, in <module>
    sys.exit(main())
  File "ez_setup.py", line 423, in main
    return _install(archive, _build_install_args(options))
  File "ez_setup.py", line 56, in _install
    with archive_context(archive_filename):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "ez_setup.py", line 107, in archive_context
    with ContextualZipFile(filename) as archive:
  File "ez_setup.py", line 91, in __new__
    return zipfile.ZipFile(*args, **kwargs)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

**Comment by dstufft** [comment]
This appears to be working, I suspect it was a temporary cache issue.
