### ISSUE TITLE
XMLRPC client search failing recently

### ISSUE THREAD

**Issue by msarahan** [pypa/warehouse#1417]
Originally filed as https://github.com/pypa/pypi-legacy/issues/500, but only occurs when xmlrpc client is pointed at https://pypi.io/pypi - thus, moved here.

Up until a couple of days ago, code like this

```
all_packages = [match["name"] for match in client.search({"name": args.packages}, "or")]
```

worked. I think this is more efficient on your servers than what the code used to be quite a while ago:

```
all_packages = client.list_packages()
```

but please correct me if I'm wrong - I'm hoping for the smallest load on your servers.

With the search code, I now get:

```
Traceback (most recent call last):
  File "/Users/msarahan/miniconda2/bin/conda-skeleton", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/msarahan/code/conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/Users/msarahan/code/conda-build/conda_build/main_skeleton.py", line 324, in main
    args_func(args, p)
  File "/Users/msarahan/code/conda-build/conda_build/main_build.py", line 415, in args_func
    args.func(args, p)
  File "/Users/msarahan/code/conda-build/conda_build/main_skeleton.py", line 341, in execute
    pypi.main(args, parser)
  File "/Users/msarahan/code/conda-build/conda_build/pypi.py", line 264, in main
    all_packages = [match["name"] for match in client.search({"name": args.packages}, "or")]
  File "/Users/msarahan/miniconda2/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/Users/msarahan/miniconda2/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/Users/msarahan/code/conda-build/conda_build/pypi.py", line 233, in request
    return self.parse_response(resp)
  File "/Users/msarahan/code/conda-build/conda_build/pypi.py", line 242, in parse_response
    ret = u.close()
  File "/Users/msarahan/miniconda2/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<type 'exceptions.KeyError'>:'hits'">
```

but the list_packages() works OK.

**Comment by msarahan** [comment]
I think the issue is that this used to work for search with URLs as the 'name' but this broke recently.  Filtering URLs before hand makes this work again.  Sorry for the noise - searching for URLs by name was bad code anyway.
