### ISSUE TITLE
Static files not rebuilding with make serve

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#2015]
On a fresh install:

Steps to reproduce:

- run `make serve`
- Edit a SCSS file
- Refresh the browser

The page is unstyled. 

The only solution I have found is to stop the containers and rerun `make serve`

**Comment by nlhkabu** [comment]
ping @dstufft :)

**Comment by nlhkabu** [comment]
error in terminal:  `rh2_static_1 exited with code 139`

**Comment by di** [comment]
I can reproduce this: after changing a file which Gulp is configured to watch, I eventually get this from the static container:

```
static_1         | FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
static_1         |
static_1         | <--- Last few GCs --->
static_1         |
static_1         |   160818 ms: Mark-sweep 1164.4 (1436.6) -> 1164.4 (1436.6) MB, 1475.6 / 0.0 ms [allocation failure] [GC in old space requested].
static_1         |   162253 ms: Mark-sweep 1164.4 (1436.6) -> 1164.4 (1436.6) MB, 1433.6 / 0.0 ms [allocation failure] [GC in old space requested].
static_1         |   163798 ms: Mark-sweep 1164.4 (1436.6) -> 1171.0 (1409.6) MB, 1543.6 / 0.0 ms [last resort gc].
static_1         |   165256 ms: Mark-sweep 1171.0 (1409.6) -> 1177.8 (1408.6) MB, 1457.1 / 0.0 ms [last resort gc].
static_1         |
static_1         |
static_1         | <--- JS stacktrace --->
static_1         |
static_1         | ==== JS stack trace =========================================
static_1         |
static_1         | Security context: 0x1c5f9cecfb39 <JS Object>
static_1         |     1: createInnerCallback [/app/node_modules/enhanced-resolve/lib/createInnerCallback.js:~5] [pc=0x13294198b86] (this=0x5dd303a4ec1 <JS Global Object>,callback=0xace0a9d5631 <JS Function afterInnerCallback (SharedFunctionInfo 0x10afd88d8a89)>,options=0x2ab43f8d09b1 <an Object with map 0x3fffbccc49a9>,message=0x2ab43f8d09e1 <String[86]: after using description file: /app/package.json (relative ...
static_1         |
static_1         |  1: node::Abort() [gulp]
static_1         |  2: 0x10c9aac [gulp]
static_1         |  3: v8::Utils::ReportApiFailure(char const*, char const*) [gulp]
static_1         |  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [gulp]
static_1         |  5: v8::internal::Handle<v8::internal::JSFunction> v8::internal::Factory::New<v8::internal::JSFunction>(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationSpace) [gulp]
static_1         |  6: v8::internal::Factory::NewFunction(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>, v8::internal::PretenureFlag) [gulp]
static_1         |  7: v8::internal::Factory::NewFunctionFromSharedFunctionInfo(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>, v8::internal::PretenureFlag) [gulp]
static_1         |  8: v8::internal::Runtime_NewClosure_Tenured(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
static_1         |  9: 0x13292c092a7
warehouse_static_1 exited with code 139
```

This is being caused by the `RootMostResolvePlugin` from the `webpack-dependency-suite`.

@nlhkabu Could you try my branch and confirm this solves your issue? https://github.com/di/warehouse/tree/remove-rootmostresolveplugin

@dstufft You added this in #1524. Do you recall why it was necessary, or was it just a safeguard? As far as I can tell everything is fine without it.

**Comment by nlhkabu** [comment]
@di I am having trouble installing your branch.  On running `make serve`:

```
Running setup.py install for paginate: started
    Running setup.py install for paginate: finished with status 'error'
    Complete output from command /usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3m3txdit/paginate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-smt1921v-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3m3txdit/paginate/setup.py", line 32, in <module>
        entry_points=""" """,
      File "/usr/local/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 321, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 389, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 859, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (packaging 16.1 (/usr/local/lib/python3.5/site-packages), Requirement.parse('packaging>=16.8'))
    
    ----------------------------------------
Command "/usr/local/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3m3txdit/paginate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-smt1921v-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3m3txdit/paginate/
ERROR: Service 'app' failed to build: The command '/bin/sh -c set -x     && apt-get update     && apt-get install gcc make libpq-dev libffi-dev --no-install-recommends -y     && rm -rf node_modules     && npm install -g bower node-gyp gulp-cli     && npm install     && pip install -U pip setuptools     && pip install -r requirements/dev.txt                    -r requirements/deploy.txt                    -r requirements/main.txt                    -r requirements/tests.txt     && find /usr/local -type f -name '*.pyc' -name '*.pyo' -delete     && rm -rf ~/.cache/     && apt-get purge gcc make libpq-dev libffi-dev -y     && apt-get autoremove -y     && apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 1
Makefile:25: recipe for target '.state/docker-build' failed
make: *** [.state/docker-build] Error 1
```

Can you reproduce, or am I doing something wrong here?

**Comment by di** [comment]
Hmm, that'd odd. I don't think it's an issue with the branch, but the branch is causing some intermediate containers to be rebuilt which is attempting to reinstall the Python dependencies.

Could you try running `make stop; make purge; make build`?

What's the output of `pip list`? Is it possible you're unintentionally in some virtualenv?

**Comment by dstufft** [comment]
@di I don't remember, the vast bulk of my touching the JS stuff is trying to guess what the right answer to make a thing work.

**Comment by dstufft** [comment]
Googling around, I seem to remember looking at this issue when I did that https://github.com/webpack/webpack/issues/985

**Comment by nlhkabu** [comment]
Thanks for this @di.  `make purge` fixed it for me.

I can confirm, the static rebuild is working again with these changes :)

**Comment by di** [comment]
@dstufft I saw that too, but as far as I can tell we don't use `npm link`, nor do we have any custom NPM modules we'd need to link. I can't see what other reason we'd need this plugin for.

I created #2027 to remove it.
