### ISSUE TITLE
Trending Projects are not updated

### ISSUE THREAD

**Issue by pradyunsg** [pypa/warehouse#3455]
I think in the past month that I've been looking at pypi.org (and even before that), the "Trending Projects" haven't changed.

**Comment by pradyunsg** [comment]
Looking further, as someone not familiar with the codebase, it seems like the `compute_trending` task isn't setup to run every day or something like that.

**Comment by brainwane** [comment]
Potentially another reason for #3252.

**Comment by dstufft** [comment]
https://github.com/pypa/warehouse/blob/ed8d6a03d86e794b83ccd4e41d0c5b6b7865b8bf/warehouse/packaging/__init__.py#L112-L115

**Comment by ewdurbin** [comment]
```
pypi-warehouse-worker-beat-856f489568-kjc9b worker-beat [2018-03-28 03:00:00,064: INFO/MainProcess] Loading 1 tasks
pypi-warehouse-worker-beat-856f489568-kjc9b worker-beat [2018-03-28 03:00:00,071: INFO/MainProcess] Scheduler: Sending due task warehouse.packaging.tasks.compute_trending() (warehouse.packaging.tasks.compute_trending)
```

I do see the task being enqueued.

**Comment by ewdurbin** [comment]
```
pypi-warehouse-worker-7b6dddfb-tlm4s worker FileNotFoundError: [Errno 2] No such file or directory: '/app/gcloud.json'
```

Looks like pathing is goof'd! will fixup!

**Comment by ewdurbin** [comment]
That was half the issue :)

Second half is they changed the API! https://github.com/GoogleCloudPlatform/google-cloud-python/blob/cd9b89ead0be95827c9eac5a9a8c5d8fdaee3cae/bigquery/CHANGELOG.md#interface-changes--breaking-changes-1

```
pypi-warehouse-worker-5c996d6869-6hbkc worker [2018-03-28 16:03:30,528: ERROR/ForkPoolWorker-2] Task warehouse.packaging.tasks.compute_trending[e6d5d345-bfb9-4fd1-a535-af52c2b1a495] raised unexpected: AttributeError("'Client' object has no attribute 'run_sync_query'",)
pypi-warehouse-worker-5c996d6869-6hbkc worker Traceback (most recent call last):
pypi-warehouse-worker-5c996d6869-6hbkc worker   File "/opt/warehouse/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
pypi-warehouse-worker-5c996d6869-6hbkc worker     R = retval = fun(*args, **kwargs)
pypi-warehouse-worker-5c996d6869-6hbkc worker   File "/opt/warehouse/src/warehouse/tasks.py", line 70, in __call__
pypi-warehouse-worker-5c996d6869-6hbkc worker     return super().__call__(*(self.get_request(),) + args, **kwargs)
pypi-warehouse-worker-5c996d6869-6hbkc worker   File "/opt/warehouse/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
pypi-warehouse-worker-5c996d6869-6hbkc worker     return self.run(*args, **kwargs)
pypi-warehouse-worker-5c996d6869-6hbkc worker   File "/opt/warehouse/src/warehouse/tasks.py", line 58, in run
pypi-warehouse-worker-5c996d6869-6hbkc worker     return original_run(*args, **kwargs)
pypi-warehouse-worker-5c996d6869-6hbkc worker   File "/opt/warehouse/src/warehouse/packaging/tasks.py", line 21, in compute_trending
pypi-warehouse-worker-5c996d6869-6hbkc worker     query = bq.run_sync_query(
pypi-warehouse-worker-5c996d6869-6hbkc worker AttributeError: 'Client' object has no attribute 'run_sync_query'
```

**Comment by brainwane** [comment]
(@pradyunsg -- *good catch* and thanks for the report!)

**Comment by ewdurbin** [comment]
Confirmed fixed.

**Comment by pradyunsg** [comment]
Yay! Thanks @ewdurbin @dstufft @brainwane for the fix. ^>^
