### ISSUE TITLE
Error running tox on OS X 10.9.5

### ISSUE THREAD

**Issue by msabramo** [pypa/warehouse#353]
Cloned the latest code and tried to run `tox -e py34`; resulted in this:

```
    Installed /Users/marca/dev/git-repos/warehouse/.tox/py34/build/bcrypt/pycparser-2.10-py3.4.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/marca/dev/git-repos/warehouse/.tox/py34/build/bcrypt/setup.py", line 255, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 973, in run_command
        cmd_obj.ensure_finalized()
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/Users/marca/dev/git-repos/warehouse/.tox/py34/build/bcrypt/setup.py", line 48, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "/Users/marca/dev/git-repos/warehouse/.tox/py34/build/bcrypt/setup.py", line 21, in get_ext_modules
        from bcrypt import _ffi
      File "/Users/marca/dev/git-repos/warehouse/.tox/py34/build/bcrypt/bcrypt/__init__.py", line 97, in <module>
        _ffi = FFI()
      File "/Users/marca/dev/git-repos/warehouse/.tox/py34/build/bcrypt/cffi-0.8.6-py3.4-macosx-10.6-intel.egg/cffi/api.py", line 56, in __init__
        import _cffi_backend as backend
    ImportError: dlopen(/Users/marca/dev/git-repos/warehouse/.tox/py34/build/bcrypt/cffi-0.8.6-py3.4-macosx-10.6-intel.egg/_cffi_backend.so, 2): Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
      Referenced from: /Users/marca/dev/git-repos/warehouse/.tox/py34/build/bcrypt/cffi-0.8.6-py3.4-macosx-10.6-intel.egg/_cffi_backend.so
      Reason: image not found
    Complete output from command /Users/marca/dev/git-repos/warehouse/.tox/py34/bin/python3.4 -c "import setuptools, tokenize;__file__='/Users/marca/dev/git-repos/warehouse/.tox/py34/build/bcrypt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/gw/w0clrs515zx9x_55zgtpv4mm0000gp/T/pip-pa3g6srh-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/marca/dev/git-repos/warehouse/.tox/py34/bin/../include/site/python3.4:
```

**Comment by msabramo** [comment]
I ultimately got this working, but it was tricky, because cffi is sort of hard to build. A few things that could help:

1. The ability to run warehouse with Docker -- https://github.com/pypa/warehouse/pull/356
2. This change to cffi to make it take advantage of Homebrew on OS X -- https://bitbucket.org/cffi/cffi/pull-request/55/os-x-with-homebrew-set-pkg_config_path/diff

**Comment by msabramo** [comment]
I figured this out. I'll close it.
