### ISSUE TITLE
XMLRPC Implementation breaks `pip search` for some clients

### ISSUE THREAD

**Issue by ewdurbin** [pypa/warehouse#3656]
outdated pip search relies on `_pypi_ordering`:

```
# Ubuntu 14.04, pip 1.5.4
$ pip search requests
Exception:
Traceback (most recent call last):
  File "/test/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/test/local/lib/python2.7/site-packages/pip/commands/search.py", line 41, in run
    hits = transform_hits(pypi_hits)
  File "/test/local/lib/python2.7/site-packages/pip/commands/search.py", line 69, in transform_hits
    score = hit['_pypi_ordering']
KeyError: '_pypi_ordering'
```

Works with latest pip:

```
# pip 9.0.3
$ pip search requests
requests (0.0.1)                         - Python HTTP for Humans.
aiohttp-requests (0.0.3)                 - A thin wrapper for aiohttp client with Requests simplicity
anonymous-requests (0.2)                 - 
....
```

*BUT* note: the search response gives an incorrect version of requests...

**Comment by brainwane** [comment]
@ewdurbin in your opinion, is this something we need to fix (either in docs or code) before we shut down legacy PyPI?

**Comment by ewdurbin** [comment]
@brainwane i'm working through remaining inconsistencies now, won't be a blocker.

**Comment by ewdurbin** [comment]
see #3670 for last few changes to match legacy xmlrpc
