### ISSUE TITLE
Infinite redirect on files.pythonhosted.org:

### ISSUE THREAD

**Issue by phihag** [pypa/warehouse#3703]
Currently, when I try to install *any* package, I get an infinite redirect:

```
$ pip install awsebcli
Collecting awsebcli
  Downloading https://files.pythonhosted.org/packages/45/fd/f0f7ff9cba9a2ab803881d7d910ea06985834eee5ce28a09329b6c1a51e3/awsebcli-3.12.4.tar.gz (247kB)
    100% |████████████████████████████████| 256kB 1.4MB/s 
Collecting blessed>=1.9.5 (from awsebcli)
Exception:
Traceback (most recent call last):                                                                                                                                          
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/download.py", line 649, in unpack_http_url
    hashes)
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/download.py", line 842, in _download_http_url
    stream=True,
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/phihag/.local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 113, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
TooManyRedirects: Exceeded 30 redirects.
You are using pip version 8.1.2, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

This seems to be a problem of files.pythonhosted.org:

```
$ curl https://files.pythonhosted.org/packages/8e/ec/9f0fd5bb3c954742eb37545297bf62bfdb46ab80e9f5beea0c1ea263fc5f/awscli-1.15.4-py2.py3-none-any.whl -i
HTTP/2 302 
server: Varnish
retry-after: 0
location: https://pypi.org/packages/8e/ec/9f0fd5bb3c954742eb37545297bf62bfdb46ab80e9f5beea0c1ea263fc5f/awscli-1.15.4-py2.py3-none-any.whl
content-type: text/html; charset=UTF-8
accept-ranges: bytes
date: Mon, 16 Apr 2018 15:24:37 GMT
age: 66
x-served-by: cache-lcy19222-LCY, cache-hhn1550-HHN
x-cache: HIT, HIT
x-cache-hits: 0, 1
x-timer: S1523892277.194156,VS0,VE0
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-frame-options: deny
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-permitted-cross-domain-policies: none
x-robots-header: noindex
content-length: 98

<html><head><title>302 Found</title></head><body><center><h1>302 Found</h1></center></body></html>
```

**Comment by ewdurbin** [comment]
duplicate #3702
