### ISSUE TITLE
Too many 503 error responses

### ISSUE THREAD

**Issue by mr-bo-jangles** [pypa/warehouse#3708]
Getting too many 503 error responses when trying to grab packages via Pip

```
    docker: Collecting apache-libcloud==2.3.0 (from -r savings_champion/requirements.txt (line 9))
    docker:   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/56/28/45a9d3bba612fc3f47ef085a14446a4f68f45ce10070562edff1e9291150/apache_libcloud-2.3.0-py2.py3-none-any.whl
    docker: Exception:
    docker: Traceback (most recent call last):
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 440, in send
    docker:     timeout=timeout
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 668, in urlopen
    docker:     **response_kw)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 732, in urlopen
    docker:     body_pos=body_pos, **response_kw)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 732, in urlopen
    docker:     body_pos=body_pos, **response_kw)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 732, in urlopen
    docker:     body_pos=body_pos, **response_kw)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 712, in urlopen
    docker:     retries = retries.increment(method, url, response=response, _pool=self)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/urllib3/util/retry.py", line 388, in increment
    docker:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
    docker: pip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/56/28/45a9d3bba612fc3f47ef085a14446a4f68f45ce10070562edff1e9291150/apache_libcloud-2.3.0-py2.py3-none-any.whl (Caused by ResponseError('too many 503 error responses',))
    docker:
    docker: During handling of the above exception, another exception occurred:
    docker:
    docker: Traceback (most recent call last):
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    docker:     status = self.run(options, args)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    docker:     wb.build(autobuilding=True)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    docker:     self.requirement_set.prepare_files(self.finder)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    docker:     ignore_dependencies=self.ignore_dependencies))
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    docker:     session=self.session, hashes=hashes)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 821, in unpack_url
    docker:     hashes=hashes
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 659, in unpack_http_url
    docker:     hashes)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 853, in _download_http_url
    docker:     stream=True,
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 521, in get
    docker:     return self.request('GET', url, **kwargs)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 386, in request
    docker:     return super(PipSession, self).request(method, url, *args, **kwargs)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 508, in request
    docker:     resp = self.send(prep, **send_kwargs)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 618, in send
    docker:     r = adapter.send(request, **kwargs)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    docker:     resp = super(CacheControlAdapter, self).send(request, **kw)
    docker:   File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 499, in send
    docker:     raise RetryError(e, request=request)
    docker: pip._vendor.requests.exceptions.RetryError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/56/28/45a9d3bba612fc3f47ef085a14446a4f68f45ce10070562edff1e9291150/apache_libcloud-2.3.0-py2.py3-none-any.whl (Caused by ResponseError('too many 503 error responses',))
```

**Comment by mr-bo-jangles** [comment]
Btw, I love the new site <3

**Comment by ewdurbin** [comment]
we're working on resolving #3707 and intermittent 503s are occurring as a result.
