### ISSUE TITLE
503 error when installing with pip

### ISSUE THREAD

**Issue by rotan96** [pypa/warehouse#3710]
I'm trying to install multiple packages with pip, and it keeps failing because of a 503 error. Here is one of the error logs.

`
-> pip install testresources
Downloading/unpacking testresources
  HTTP error 503 while getting https://files.pythonhosted.org/packages/45/4d/79a9a1f71de22fbc6c6433ac135f68d005de72fbe73e2137d2e77da9252c/testresources-2.0.1-py2.py3-none-any.whl#sha256=67a361c3a2412231963b91ab04192209aa91a1aa052f0ab87245dbea889d1282 (from https://pypi.org/simple/testresources/)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 547, in unpack_http_url
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 503 Server Error: Backend is unhealthy
`

**Comment by davisagli** [comment]
duplicate #3708

**Comment by ewdurbin** [comment]
tracking in #3705
