### ISSUE TITLE
PyPI's files.pythonhosted.org outage

### ISSUE THREAD

**Issue by jimmyzhen** [pypa/warehouse#3735]
I am creating this ticket in reference to https://github.com/pypa/setuptools/issues/1331 because I am still experience the same problem as reported as of this morning:

```
$ python3.4 bootstrap.py -v 2.9.5 --setuptools-version 15.2
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-15.2.zip
Extracting in /var/folders/nb/wf4l644d6r11zjp0btpq6wkw0000gp/T/tmpcbn76a27
Traceback (most recent call last):
  File "bootstrap.py", line 105, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 170, in use_setuptools
  File "<string>", line 122, in _do_download
  File "<string>", line 62, in _build_egg
  File "/Users/jzhen/.pyenv/versions/3.4.1/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "<string>", line 101, in archive_context
  File "<string>", line 85, in __new__
  File "/Users/jzhen/.pyenv/versions/3.4.1/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/Users/jzhen/.pyenv/versions/3.4.1/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by ewdurbin** [comment]
hi @jimmyzhen it's not clear that this is related to the files.pythonhosted.org incident yesterday, that had symptoms of redirect loops, 404s, and 503s. this appears to either be a corrupt file or error in handling such a file.

It is also possible that the bootstrap script is not appropriately following the redirect.

I've verified that the file served from pypi, (https://files.pythonhosted.org/packages/28/17/f1b300eeec0405388bfffc51a1efb37c45ad713c978b231f2c24e1a7cee4/setuptools-15.2.zip) is accessible and has the correct checksum.

This is a setuptools or bootstrap.py bug.

**Comment by di** [comment]
Issue in setuptools is here: https://github.com/pypa/setuptools/issues/1331

**Comment by jimmyzhen** [comment]
Thanks, @ewdurbin!
