### ISSUE TITLE
XML-RPC getting redirects for /RPC2

### ISSUE THREAD

**Issue by di** [pypa/warehouse#3736]
```
>>> proxy = xmlrpclib.ServerProxy("http://pypi.org")
>>> proxy.search({'name': 'hi'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/di/.pyenv/versions/2.7.12/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/Users/di/.pyenv/versions/2.7.12/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/Users/di/.pyenv/versions/2.7.12/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/Users/di/.pyenv/versions/2.7.12/lib/python2.7/xmlrpclib.py", line 1331, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for pypi.org/RPC2: 301 Moved Permanently>
```

This wasn't happening before the launch.

**Comment by dstufft** [comment]
It's redirecting the http to https, it's been doing that for a _long_ time.

**Comment by di** [comment]
Whoops... haven't had my coffee yet.
