### ISSUE TITLE
No module named 'pymongo.change_stream'

### ISSUE THREAD

**Issue by andrewisakov** [pypa/warehouse#3749]
>>> import motor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/.local/lib64/python3.6/site-packages/motor/__init__.py", line 54, in <module>
    from .motor_tornado import *
  File "/home/andrew/.local/lib64/python3.6/site-packages/motor/motor_tornado.py", line 19, in <module>
    from . import core, motor_gridfs
  File "/home/andrew/.local/lib64/python3.6/site-packages/motor/core.py", line 34, in <module>
    from pymongo.change_stream import ChangeStream
ModuleNotFoundError: No module named 'pymongo.change_stream'

>>> import pymongo.change_stream
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pymongo.change_stream'

But,
>>> import pymongo
is OK

**Comment by jamadden** [comment]
Thank you for your report. Unfortunately this is not the correct place for it. This tracker is only for issues with the code that runs pypi.org itself. It cannot help with packages installed from there or general Python usage. You might try contacting [the motor developers](https://pypi.org/project/motor/).
