### ISSUE TITLE
pip via system package python-pip broken since upgrade (ubuntu 14.04)

### ISSUE THREAD

**Issue by LarsFronius** [pypa/warehouse#3769]
The following is happening when I try to install/upgrade any package on my box running the latest Ubuntu 14.04:
```
root@ubuntu:~# pip install pip --upgrade
Downloading/unpacking requests from https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl#sha256=6a1b267aa90cac58ac3a765d067950e7dbbf75b1da07e895d1f594193a40a38b
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 546, in unpack_http_url
    resp = session.get(target_url, stream=True)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 562, in urlopen
    body=body, headers=headers)
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 145, in connect
    match_hostname(self.sock.getpeercert(),
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 313, in getpeercert
    for value in get_subj_alt_name(x509)
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 94, in get_subj_alt_name
    asn1Spec=general_names)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 1160, in __call__
    **options
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 532, in valueDecoder
    asn1Object.verifySizeSpec()
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/base.py", line 574, in verifySizeSpec
    self.sizeSpec(self)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/constraint.py", line 39, in __call__
    '%s failed at: %r' % (self, sys.exc_info()[1])
ValueConstraintError: ConstraintsIntersection(ValueSizeConstraint(1, 64)) failed at: ValueConstraintError("ValueSizeConstraint(1, 64) failed at: ValueConstraintError(SubjectAltName().setComponentByPosition(0, GeneralName().setComponentByPosition(2, IA5String(u'r.ssl.fastly.net', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(1, GeneralName().setComponentByPosition(2, IA5String(u'*.addthis.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(2, GeneralName().setComponentByPosition(2, IA5String(u'*.addthisedge.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(3, GeneralName().setComponentByPosition(2, IA5String(u'*.adwerx.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(4, GeneralName().setComponentByPosition(2, IA5String(u'*.alittlecraft.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(5, GeneralName().setComponentByPosition(2, IA5String(u'*.alittlecraft.it', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(6, GeneralName().setComponentByPosition(2, IA5String(u'*.alittlemarket.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(7, GeneralName().setComponentByPosition(2, IA5String(u'*.alittlemarket.it', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(8, GeneralName().setComponentByPosition(2, IA5String(u'*.alittlemercerie.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(9, GeneralName().setComponentByPosition(2, IA5String(u'*.bighatads.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(10, GeneralName().setComponentByPosition(2, IA5String(u'*.buzzfeed.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(11, GeneralName().setComponentByPosition(2, IA5String(u'*.catchpoint.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(12, GeneralName().setComponentByPosition(2, IA5String(u'*.cnn.io', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(13, GeneralName().setComponentByPosition(2, IA5String(u'*.corednacdn.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(14, GeneralName().setComponentByPosition(2, IA5String(u'*.dollarshaveclub.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(15, GeneralName().setComponentByPosition(2, IA5String(u'*.domfee.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(16, GeneralName().setComponentByPosition(2, IA5String(u'*.eater.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(17, GeneralName().setComponentByPosition(2, IA5String(u'*.fastlylabs.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(18, GeneralName().setComponentByPosition(2, IA5String(u'*.files.saymedia-content.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(19, GeneralName().setComponentByPosition(2, IA5String(u'*.finncdn.no', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(20, GeneralName().setComponentByPosition(2, IA5String(u'*.ft.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(21, GeneralName().setComponentByPosition(2, IA5String(u'*.geonet.org.nz', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(22, GeneralName().setComponentByPosition(2, IA5String(u'*.hipmunkstaging.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(23, GeneralName().setComponentByPosition(2, IA5String(u'*.houselogic.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(24, GeneralName().setComponentByPosition(2, IA5String(u'*.issuu.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(25, GeneralName().setComponentByPosition(2, IA5String(u'*.isu.pub', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(26, GeneralName().setComponentByPosition(2, IA5String(u'*.jackthreads.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(27, GeneralName().setComponentByPosition(2, IA5String(u'*.lostmy.name', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(28, GeneralName().setComponentByPosition(2, IA5String(u'*.meetupstatic.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(29, GeneralName().setComponentByPosition(2, IA5String(u'*.netzwelt.de', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(30, GeneralName().setComponentByPosition(2, IA5String(u'*.nfl.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(31, GeneralName().setComponentByPosition(2, IA5String(u'*.pagar.me', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(32, GeneralName().setComponentByPosition(2, IA5String(u'*.picmonkey.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(33, GeneralName().setComponentByPosition(2, IA5String(u'*.pypi.io', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(34, GeneralName().setComponentByPosition(2, IA5String(u'*.pypi.org', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(35, GeneralName().setComponentByPosition(2, IA5String(u'*.pythonhosted.org', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(36, GeneralName().setComponentByPosition(2, IA5String(u'*.r29static.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(37, GeneralName().setComponentByPosition(2, IA5String(u'*.realself.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(38, GeneralName().setComponentByPosition(2, IA5String(u'*.rtbf.be', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(39, GeneralName().setComponentByPosition(2, IA5String(u'*.sbnation.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(40, GeneralName().setComponentByPosition(2, IA5String(u'*.shakr.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(41, GeneralName().setComponentByPosition(2, IA5String(u'*.shiftpreview.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(42, GeneralName().setComponentByPosition(2, IA5String(u'*.static.rtbf.be', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(43, GeneralName().setComponentByPosition(2, IA5String(u'*.streamable.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(44, GeneralName().setComponentByPosition(2, IA5String(u'*.surfly.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(45, GeneralName().setComponentByPosition(2, IA5String(u'*.theverge.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(46, GeneralName().setComponentByPosition(2, IA5String(u'*.thrillist.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(47, GeneralName().setComponentByPosition(2, IA5String(u'*.tissuu.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(48, GeneralName().setComponentByPosition(2, IA5String(u'*.vox-cdn.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(49, GeneralName().setComponentByPosition(2, IA5String(u'*.vox.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(50, GeneralName().setComponentByPosition(2, IA5String(u'*.voxmedia.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(51, GeneralName().setComponentByPosition(2, IA5String(u'*.w-x.co', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(52, GeneralName().setComponentByPosition(2, IA5String(u'*.watch.aetnd.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(53, GeneralName().setComponentByPosition(2, IA5String(u'*.wework.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(54, GeneralName().setComponentByPosition(2, IA5String(u'*.wired.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(55, GeneralName().setComponentByPosition(2, IA5String(u'adwerx.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(56, GeneralName().setComponentByPosition(2, IA5String(u'alittlecraft.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(57, GeneralName().setComponentByPosition(2, IA5String(u'alittlecraft.it', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(58, GeneralName().setComponentByPosition(2, IA5String(u'alittlemarket.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(59, GeneralName().setComponentByPosition(2, IA5String(u'alittlemarket.it', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(60, GeneralName().setComponentByPosition(2, IA5String(u'alittlemercerie.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(61, GeneralName().setComponentByPosition(2, IA5String(u'alpha.entrepreneur.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(62, GeneralName().setComponentByPosition(2, IA5String(u'api.shiftcommerce.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(63, GeneralName().setComponentByPosition(2, IA5String(u'assets-staging.themuse.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(64, GeneralName().setComponentByPosition(2, IA5String(u'assets.themuse.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(65, GeneralName().setComponentByPosition(2, IA5String(u'buzzfeed.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(66, GeneralName().setComponentByPosition(2, IA5String(u'dev.api.cerebro.cnn.io', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(67, GeneralName().setComponentByPosition(2, IA5String(u'dev.historyvault.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(68, GeneralName().setComponentByPosition(2, IA5String(u'dev.lifetimemovieclub.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(69, GeneralName().setComponentByPosition(2, IA5String(u'eater.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(70, GeneralName().setComponentByPosition(2, IA5String(u'entrepreneur.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(71, GeneralName().setComponentByPosition(2, IA5String(u'fastly.shiekhdev.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(72, GeneralName().setComponentByPosition(2, IA5String(u'ft.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(73, GeneralName().setComponentByPosition(2, IA5String(u'h2.hipmunkstaging.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(74, GeneralName().setComponentByPosition(2, IA5String(u'h2.saladly.net', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(75, GeneralName().setComponentByPosition(2, IA5String(u'i.gse.io', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(76, GeneralName().setComponentByPosition(2, IA5String(u'lostmy.name', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(77, GeneralName().setComponentByPosition(2, IA5String(u'preview.entrepreneur.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(78, GeneralName().setComponentByPosition(2, IA5String(u'pythonhosted.org', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(79, GeneralName().setComponentByPosition(2, IA5String(u'qa.safariflow.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(80, GeneralName().setComponentByPosition(2, IA5String(u'realself.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(81, GeneralName().setComponentByPosition(2, IA5String(u'red-www.nicolevienna.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(82, GeneralName().setComponentByPosition(2, IA5String(u'rtbf.be', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(83, GeneralName().setComponentByPosition(2, IA5String(u'ssl.netzwelt.de', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(84, GeneralName().setComponentByPosition(2, IA5String(u'stag2.wired.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(85, GeneralName().setComponentByPosition(2, IA5String(u'stag3.wired.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(86, GeneralName().setComponentByPosition(2, IA5String(u'stag4.wired.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(87, GeneralName().setComponentByPosition(2, IA5String(u'static.refinery29.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(88, GeneralName().setComponentByPosition(2, IA5String(u'static.wixstatic.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(89, GeneralName().setComponentByPosition(2, IA5String(u'streamable.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(90, GeneralName().setComponentByPosition(2, IA5String(u'surfly.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(91, GeneralName().setComponentByPosition(2, IA5String(u'theverge.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(92, GeneralName().setComponentByPosition(2, IA5String(u'ticketcity.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(93, GeneralName().setComponentByPosition(2, IA5String(u'vox-cdn.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(94, GeneralName().setComponentByPosition(2, IA5String(u'vox.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(95, GeneralName().setComponentByPosition(2, IA5String(u'wired.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(96, GeneralName().setComponentByPosition(2, IA5String(u'www.dexigner.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(97, GeneralName().setComponentByPosition(2, IA5String(u'www.entrepreneur.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(98, GeneralName().setComponentByPosition(2, IA5String(u'www.joyent.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(99, GeneralName().setComponentByPosition(2, IA5String(u'www.qa.safariflow.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(100, GeneralName().setComponentByPosition(2, IA5String(u'www.stackpop.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))).setComponentByPosition(101, GeneralName().setComponentByPosition(2, IA5String(u'www.ticketcity.com', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2))))),)",)

Storing debug log for failure in /root/.pip/pip.log
```
```
root@ubuntu:~# pip -V
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```
```
root@ubuntu:~# apt-cache policy python-pip
python-pip:
  Installed: 1.5.4-1ubuntu4
  Candidate: 1.5.4-1ubuntu4
  Version table:
 *** 1.5.4-1ubuntu4 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     1.5.4-1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```
I am assuming this is due to cert/CDN switches made on the upstream repository. Any guidance how I get the system version back to life is much appreciated. Obviously, simply installing a fresh version of `pip` fixes the issue - however, since this is the default ubuntu 14.04 pip version I am wondering what else could be done.

**Comment by di** [comment]
@LarsFronius I think you'd probably get better support for this issue if you opened it over at https://github.com/pypa/pip/issues instead, although I suspect they're going to tell you that since this is such an old version of `pip`, you'd be better off incrementally upgrading it (although perhaps this is related to https://github.com/pypa/pip/issues/1488?)

**Comment by motwanideepika-ee** [comment]
@LarsFronius did you get any solution to this issue? I am facing a similar issue

**Comment by SrivigneshM** [comment]
> @LarsFronius did you get any solution to this issue? I am facing a similar issue

Below solution worked for me.

Uninstall pip2
Install pip2 using PyPI (Refer 'Install pip From PyPI' section in https://www.howtodojo.com/2016/03/install-use-pip-ubuntu-14-04/) Note: Install from ubuntu repository didn't work in my case.
Then I no longer got ValueConstraintError while installing any module using pip2 (ex: pip2 install invoke)
