### ISSUE TITLE
Numba dependency pegged to erroneous install of llvmlite

### ISSUE THREAD

**Issue by sarahmtynes** [pypa/warehouse#3808]
The latest release of Numba pegs an llvmlite dependency to llvmlite>=0.23.0dev0; however, running a pip install for llvmlite produces the following error:

```
 LLVM version... Traceback (most recent call last):
      File "/private/tmp/pip-install-t7j70pxu/llvmlite/ffi/build.py", line 91, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/private/tmp/pip-install-t7j70pxu/llvmlite/ffi/build.py", line 143, in <module>
        main()
      File "/private/tmp/pip-install-t7j70pxu/llvmlite/ffi/build.py", line 137, in main
        main_posix('osx', '.dylib')
      File "/private/tmp/pip-install-t7j70pxu/llvmlite/ffi/build.py", line 94, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
```

Numba itself is a dependency of fastparquet, meaning that the installation of fastparquet is also broken.

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately this is not the correct place for it. This tracker is only for issues with the software that runs pypi.org itself; it cannot help with packages distributed (or pip install-ed) from there. You'll need to contact the Numba or llvmlite developers instead.

Just based on the traceback, it looks like a problem on your system. You'll need to make sure llvm is properly installed and that `llvm-config` is on your path or set the environment variable LLVM_CONFIG to the location of that program. I'm guessing it would be something like `/usr/local/Cellar/bin/llvm-config`, so your command would be something like `LLVM_CONFIG=/usr/local/Cellar/llvm-config pip install llvmlite`.
