### ISSUE TITLE
Cannot install pip packages

### ISSUE THREAD

**Issue by Tonkonozhenko** [pypa/warehouse#3826]
Hi

I get next error when trying to install package:

```
(.venv) ➜  ml pip install scipy 
Looking in indexes: https://pypi.org/simple, https://xxxxxxx/pypi/packages
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/9a/3f/fb702aa44220014ee8803a5a0bb597e133a512d75d21463d1a2267c059df/scipy-1.0.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.4MB)
    4% |█▍                              | 727kB 121kB/s eta 0:02:10Exception:
Traceback (most recent call last):
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 310, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 674, in unpack_http_url
    progress_bar)
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 898, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 618, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 48, in check_against_chunks
    for chunk in chunks:
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 586, in written_chunks
    for chunk in chunks:
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/utils/ui.py", line 159, in iter
    for x in it:
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 575, in resp_read
    decode_content=False):
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 307, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

**Comment by Tonkonozhenko** [comment]
Now that command worked, but I hope stacktrace will be useful for you.

**Comment by ewdurbin** [comment]
Hello @Tonkonozhenko! Was this error reproducible more than once? Occasional timeouts will happen.

If this was reproducible for any duration of time we may need to do some tuning of our CDN configuration.

**Comment by Tonkonozhenko** [comment]
Hi @di 
Yes, and I experience same issues from my Jenkins (AWS eu-west-1 - Ireland):

```
Collecting retrying==1.3.3 (from -r requirements.txt (line 47))
  Could not find a version that satisfies the requirement retrying==1.3.3 (from -r requirements.txt (line 47)) (from versions: )
No matching distribution found for retrying==1.3.3 (from -r requirements.txt (line 47))
```

**Comment by Tonkonozhenko** [comment]
@di now it works. On jenkins I get messages about different packages each time. Today I got 
```
Collecting pycparser==2.18 (from -r requirements.txt (line 37))
  Could not find a version that satisfies the requirement pycparser==2.18 (from -r requirements.txt (line 37)) (from versions: )
No matching distribution found for pycparser==2.18 (from -r requirements.txt (line 37))
```

Most often I get messages about `futures==3.2.0`.

**Comment by ssbarnea** [comment]
Since mid-April migration to the CDN, we see these errors quite often, probably in 1-3% of builds (which is a huge number). There is nothing special about the package name, the seem to be random and apparently pip does not attempt to retry, it just fail with the conclusion that there are no packages at all. This failed even with not pinned or open ranges, looks like an index requires returns nothing or an error is treated as a 404.

Since two hours ago I eneabled ``PIP_VERBOSE=1`` and I hope that soon I will have more detailed output.

**Comment by ssbarnea** [comment]
I already started to get failure results, see https://gist.github.com/ssbarnea/78df2a80137cca04ca72872b1d14498f as the last failure with extra logging.

**Comment by di** [comment]
@ssbarnea Can you provide the command which produced that output? I would expect there to be more output from pip about trying to install the `deprecation` package.

**Comment by ssbarnea** [comment]
@di I updated the gist with a more detailed one. What was the original install command is irrelevant as the is no way to reproduce the problem in a consistent way. Talke at look at https://gist.github.com/ssbarnea/78df2a80137cca04ca72872b1d14498f#file-pypi-pip-failure-log-L34

My impression is that this explains what happens:
```
  https://pypi.org:443 "GET /simple/deprecation/ HTTP/1.1" 304 0
  Skipping page https://pypi.org/simple/deprecation/ because of Content-Type: unknown
```
Mainly pip decides that there is no package when it does receive a 304 response.

**Comment by njsmith** [comment]
See also: https://github.com/pypa/pip/issues/5345

**Comment by hashimyousaf** [comment]
You should try this , This command command worked for me .
sudo pip install --default-timeout=100 future

**Comment by noorkhokhar99** [comment]
> Hi
> 
> I get next error when trying to install package:
> 
> ```
> (.venv) ➜  ml pip install scipy 
> Looking in indexes: https://pypi.org/simple, https://xxxxxxx/pypi/packages
> Collecting scipy
>   Downloading https://files.pythonhosted.org/packages/9a/3f/fb702aa44220014ee8803a5a0bb597e133a512d75d21463d1a2267c059df/scipy-1.0.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.4MB)
>     4% |█▍                              | 727kB 121kB/s eta 0:02:10Exception:
> Traceback (most recent call last):
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 302, in _error_catcher
>     yield
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 384, in read
>     data = self._fp.read(amt)
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 60, in read
>     data = self.__fp.read(amt)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 449, in read
>     n = self.readinto(b)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 493, in readinto
>     n = self.fp.readinto(b)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
>     return self._sock.recv_into(b)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1009, in recv_into
>     return self.read(nbytes, buffer)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 871, in read
>     return self._sslobj.read(len, buffer)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 631, in read
>     v = self._sslobj.read(len, buffer)
> socket.timeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
>     status = self.run(options, args)
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 291, in run
>     resolver.resolve(requirement_set)
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 103, in resolve
>     self._resolve_one(requirement_set, req)
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
>     abstract_dist = self._get_abstract_dist_for(req_to_install)
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
>     self.require_hashes
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 310, in prepare_linked_requirement
>     progress_bar=self.progress_bar
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 837, in unpack_url
>     progress_bar=progress_bar
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 674, in unpack_http_url
>     progress_bar)
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 898, in _download_http_url
>     _download_url(resp, link, content_file, hashes, progress_bar)
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 618, in _download_url
>     hashes.check_against_chunks(downloaded_chunks)
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 48, in check_against_chunks
>     for chunk in chunks:
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 586, in written_chunks
>     for chunk in chunks:
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/utils/ui.py", line 159, in iter
>     for x in it:
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_internal/download.py", line 575, in resp_read
>     decode_content=False):
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 436, in stream
>     data = self.read(amt=amt, decode_content=decode_content)
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 401, in read
>     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/Users/alex/projects/stuff-meta/ml/.venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 307, in _error_catcher
>     raise ReadTimeoutError(self._pool, None, 'Read timed out.')
> pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
> ```


you can  try.
>pip install --default-timeout=1000 package name.

**Comment by biniamabebe** [comment]
i get the same error too

Traceback (most recent call last):
  File "c:\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 360, in _error_catcher
    yield
  File "c:\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 442, in read
    data = self._fp.read(amt)
  File "c:\python\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\python\lib\http\client.py", line 447, in read
    n = self.readinto(b)
  File "c:\python\lib\http\client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "c:\python\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\python\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "c:\python\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in main
    status = self.run(options, args)
  File "c:\python\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "c:\python\lib\site-packages\pip\_internal\resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\python\lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\python\lib\site-packages\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "c:\python\lib\site-packages\pip\_internal\operations\prepare.py", line 334, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "c:\python\lib\site-packages\pip\_internal\download.py", line 878, in unpack_url
    progress_bar=progress_bar
  File "c:\python\lib\site-packages\pip\_internal\download.py", line 702, in unpack_http_url
    progress_bar)
  File "c:\python\lib\site-packages\pip\_internal\download.py", line 946, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "c:\python\lib\site-packages\pip\_internal\download.py", line 639, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "c:\python\lib\site-packages\pip\_internal\utils\hashes.py", line 62, in check_against_chunks
    for chunk in chunks:
  File "c:\python\lib\site-packages\pip\_internal\download.py", line 607, in written_chunks
    for chunk in chunks:
  File "c:\python\lib\site-packages\pip\_internal\utils\ui.py", line 159, in iter
    for x in it:
  File "c:\python\lib\site-packages\pip\_internal\download.py", line 596, in resp_read
    decode_content=False):
  File "c:\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\python\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by biniamabebe** [comment]
> pip install --default-timeout=1000 package name.

this one works  !!!

**Comment by dnlsfq** [comment]
e.g.

pip install --default-timeout=1000 <package_name>

pip install --default-timeout=1000 scipy

pip install --default-timeout=1000 widgetsnbextension

**Comment by di** [comment]
If anyone is still experiencing this, please file a [new Network Access issue](https://github.com/pypa/warehouse/issues/new?template=access-issues.md).
