### ISSUE TITLE
XMLRPC search fails when there's an empty summary

### ISSUE THREAD

**Issue by pradyunsg** [pypa/warehouse#4074]
**Describe the bug**
A package with an empty summary causes the XMLRPC request for `search` to fail. One such package is [`pam`](https://pypi.org/project/pam/).

**Expected behavior**
The XMLRPC request should not fail.

**To Reproduce**
Run the following script on any Python 3 interpreter:

```py
from xmlrpc.client import ServerProxy

client = ServerProxy('https://pypi.python.org/pypi')
client.search({'name': 'pam'})
```

You would get a traceback like:

```pytb
Traceback (most recent call last):
  File "/tmp/foo.py", line 5, in <module>
    client.search({'name': 'pam'})
  File "/usr/[blah blah]/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/[blah blah]/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/[blah blah]/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/[blah blah]/lib/python3.6/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/[blah blah]/lib/python3.6/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/[blah blah]/lib/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: 'application error'>
```

**My Platform**
Not relevant.

**Additional context**
From pypa/pip#5435

**Comment by jhermann** [comment]
The (likely) fix:

```diff
diff --git a/warehouse/legacy/api/xmlrpc/views.py b/warehouse/legacy/api/xmlrpc/views.py
index 542e6da6..4e26d00e 100644
--- a/warehouse/legacy/api/xmlrpc/views.py
+++ b/warehouse/legacy/api/xmlrpc/views.py
@@ -131,7 +131,7 @@ def search(request, spec, operator="and"):
         return [
             {
                 "name": r.name,
-                "summary": getattr(r, 'summary'),
+                "summary": getattr(r, 'summary', ''),
                 "version": v,
                 "_pypi_ordering": False
             }
@@ -142,7 +142,7 @@ def search(request, spec, operator="and"):
     return [
         {
             "name": r.name,
-            "summary": getattr(r, 'summary'),
+            "summary": getattr(r, 'summary', ''),
             "version": r.latest_version,
             "_pypi_ordering": False
         }
```
Possibly ``getattr(r, 'summary', None) or ''`` instead, to ensure that a string is delivered in any case.

**Comment by pradyunsg** [comment]
Closing in favor of #4028
