### ISSUE TITLE
pythonhosted.org has outdated files

### ISSUE THREAD

**Issue by GerBreOwn** [pypa/warehouse#4150]
I am trying to use pip install django2.0.6 and it goes to files.pythonhosted.org which has as the latest django1.11.13
How can I make it download/install from PyPi instead of pythonhosted.org?
Thanks

**Describe the bug**
OLD versions are being downloaded

**Expected behavior**

I expect the LATEST version to be downloaded

**To Reproduce**

pip install django or pip install django-2.0.6  always goes to files.pythonhosted.org and django-1.11.13

**My Platform**
Linux Mint 18.3
PIP 10.0.1

**Additional context**

**Comment by jamadden** [comment]
By visiting https://pypi.org/project/django and clicking on 'download files' we can see that the latest files for 2.0.6 are indeed hosted on files.pythonhosted.org, for example https://files.pythonhosted.org/packages/08/2b/a6a12fa67a9d52a8f5ef929337165dcc5842a4461a87fec94eb6345fed57/Django-2.0.6.tar.gz

But we can also see in the 'Meta' section that django 2.0.6 "Requires: Python >=3.4". If you're using pip on an older version of Python than 3.4, pip will find the latest versions that's compatibly with your version of Python. For Python 2.7, that's 1.11.13.

You don't say what version of Python you're using, but I'll bet it's something older than 3.4.

**Comment by ewdurbin** [comment]
😅 whoops

**Comment by GerBreOwn** [comment]
You are correct that my python version was the **OLD** 2.7 version of Python.  I found an article to alias my version to 3.6.5, which I did, however I am still getting the same error.  See the following:

 python -V
Python 3.6.5
(simonproj) gerald@gerald-HP-Linux-Mint /media/gerald/Projects/simonproj $ pip install -r requirements.txt
Collecting django (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/25/4d/c8228419346a0e84aec202a43e181afc6572b861d38f8a0306dbce6abef0/Django-1.11.13-py2.py3-none-any.whl
Collecting gunicorn (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/55/cb/09fe80bddf30be86abfc06ccb1154f97d6c64bb87111de066a5fc9ccb937/gunicorn-19.8.1-py2.py3-none-any.whl
Collecting pymysql (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/32/e8/222d9e1c7821f935d6dba8d4c60b9985124149b35a9f93a84f0b98afc219/PyMySQL-0.8.1-py2.py3-none-any.whl
Collecting mysqlclient (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Hgct0d/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-Hgct0d/mysqlclient/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-install-Hgct0d/mysqlclient/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Hgct0d/mysqlclient/

This this is running in Linux Mint 18.3.  I also have Ubuntu 18.04 installed on this system and it does NOT have these problems.

BTW, thanks for the quick response.

**Comment by jamadden** [comment]
Just because you have the `python` command "aliased" does not mean that the `pip` command is similarly "aliased." You would typically need to be in a [virtual environment](http://docs.python-guide.org/en/latest/dev/virtualenvs/) for that to be true. 

Instead of `pip ...` you might try `python -m pip ...`. That way you can be reasonably sure that the version of Python running pip is what you expect.

However, I suspect you're going to have a more serious problem with this requirments.txt. You are attempting to install `mysqlclient` but it is failing with `EnvironmentError: mysql_config not found`. I believe that means that the MySQL database is not correctly installed, so you'll also need to do that., which is well beyond the scope of what this tracker can help with, sorry.

Good luck!

**Comment by ewdurbin** [comment]
@GerBreOwn any luck here?

**Comment by di** [comment]
Closing due to inactivity, feel free to reopen if this is still an issue.
