### ISSUE TITLE
AttributeError: 'module' object has no attribute 'AdminMediaHandler'

### ISSUE THREAD

**Issue by satyadasari44** [pypa/warehouse#4278]
(env) C:\Python27\source_code\django_cherrypy\myproject> python manage.py runwsgiserver
starting server with options {'autoreload': False, 'ssl_certificate': None, 'workdir': None, 'server_name': 'localhost', 'host': '127.0.0.1', 'daemonize': False,
'threads': 10, 'pidfile': None, 'ssl_private_key': None, 'adminserve': True, 'server_group': 'www-data', 'port': 8000, 'server_user': 'www-data'}
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\source_code\django_cherrypy\env\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Python27\source_code\django_cherrypy\env\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\source_code\django_cherrypy\env\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\source_code\django_cherrypy\env\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Python27\source_code\django_cherrypy\env\lib\site-packages\django_wsgiserver\management\commands\runwsgiserver.py", line 89, in handle
    runwsgiserver(args)
  File "C:\Python27\source_code\django_cherrypy\env\lib\site-packages\django_wsgiserver\management\commands\runwsgiserver.py", line 304, in runwsgiserver
    start_server_servestatic(options)
  File "C:\Python27\source_code\django_cherrypy\env\lib\site-packages\django_wsgiserver\management\commands\runwsgiserver.py", line 237, in start_server_servestat
ic
    app = django.core.servers.basehttp.AdminMediaHandler(app)
AttributeError: 'module' object has no attribute 'AdminMediaHandler'

**Comment by jamadden** [comment]
Thanks for the report, but unfortuantely this is not the place for it. This tracker is only for issues with the software that runs pypi.org itself. It cannot help with support requests or issues in packages installed from there. You'll need to find the support channels for the package you're having trouble with. There are some help suggestions for django on its [project page](https://pypi.org/project/Django/).
