### ISSUE TITLE
py2exe not working on Python3.7

### ISSUE THREAD

**Issue by telli01** [pypa/warehouse#4305]
**Describe the bug**

py2exe does not support python 3.7

while trying to make an exe_file from "FileManager.py" I get the following error:

PS C:\Users\telli\Desktop\FileMaker> py -3.7 -m py2exe.build_exe -s .\FileManager.py
Traceback (most recent call last):
  File "C:\Users\telli\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\telli\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\telli\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\build_exe.py", line 145, in <module>
    main()
  File "C:\Users\telli\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\build_exe.py", line 141, in main
    builder.analyze()
  File "C:\Users\telli\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\runtime.py", line 160, in analyze
    self.mf.import_hook(modname)
  File "C:\Users\telli\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "C:\Users\telli\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\telli\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "C:\Users\telli\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 388, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "C:\Users\telli\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py2exe\mf3.py", line 417, in _scan_opcodes
    yield "store", (names[oparg],)
IndexError: tuple index out of range

**Expected behavior**

make an exe_file out of given python script

**To Reproduce**

try py2exe with python 3.7

**My Platform**

windows 10

**Additional context**

**Comment by RonnyPfannschmidt** [comment]
i fail to see how this is a issue with warehouse

**Comment by di** [comment]
Hi @telli01, sorry you're having problems. Unfortunately this is not the right place for a bug report about `py2exe` -- this tracker is only for issues with the software that runs pypi.org itself. It cannot help with support requests or issues in packages installed from there.

You'll need to find the support channels for the package you're having trouble with. It looks like this mailing list might be a good bet: https://sourceforge.net/projects/py2exe/lists/py2exe-users

**Comment by telli01** [comment]
Hi,

Thanks for mentioning. I didn’t realize that. Have a nice day.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Dustin Ingram <notifications@github.com>
Gesendet: Tuesday, July 17, 2018 4:51:56 AM
An: pypa/warehouse
Cc: Gökhan Yesilyayla; Mention
Betreff: Re: [pypa/warehouse] py2exe not working on Python3.7 (#4305)


Hi @telli01<https://github.com/telli01>, sorry you're having problems. Unfortunately this is not the right place for a bug report about py2exe -- this tracker is only for issues with the software that runs pypi.org itself. It cannot help with support requests or issues in packages installed from there.

You'll need to find the support channels for the package you're having trouble with. It looks like this mailing list might be a good bet: https://sourceforge.net/projects/py2exe/lists/py2exe-users
