### ISSUE TITLE
"warehouse init config.py" failing when setting up

### ISSUE THREAD

**Issue by ncoghlan** [pypa/warehouse#444]
I'm not sure if this is a README bug, a missing dependency, a user error or an actual bug, but after using "mkvirtualenv -p /usr/bin/python3 warehouse" to create a virtualenv and running "pip install -r requirements.txt", I get the following when running "warehouse init config.py":

```
Traceback (most recent call last):
  File "/home/ncoghlan/.virtualenvs/warehouse/bin/warehouse", line 9, in <module>
    load_entry_point('warehouse==0.1dev1', 'console_scripts', 'warehouse')()
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python3.4/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python3.4/site-packages/pkg_resources.py", line 2431, in load_entry_point
    return ep.load()
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python3.4/site-packages/pkg_resources.py", line 2147, in load
    ['__name__'])
  File "/home/ncoghlan/devel/warehouse/warehouse/__main__.py", line 15, in <module>
    from configurations import management
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python3.4/site-packages/configurations/__init__.py", line 2, in <module>
    from .base import Settings, Configuration
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python3.4/site-packages/configurations/base.py", line 7, in <module>
    from .utils import uppercase_attributes
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python3.4/site-packages/configurations/utils.py", line 5, in <module>
    from django.utils.importlib import import_module
ImportError: No module named 'django.utils.importlib'
```

I initially tried Python 2, and that failed in the same way (just with a misleading exception message that initially made me think it wanted Python 3's importlib module):

```
Traceback (most recent call last):
  File "/home/ncoghlan/.virtualenvs/warehouse/bin/warehouse", line 9, in <module>
    load_entry_point('warehouse==0.1dev1', 'console_scripts', 'warehouse')()
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python2.7/site-packages/pkg_resources.py", line 2431, in load_entry_point
    return ep.load()
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python2.7/site-packages/pkg_resources.py", line 2147, in load
    ['__name__'])
  File "/home/ncoghlan/devel/warehouse/warehouse/__main__.py", line 15, in <module>
    from configurations import management
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python2.7/site-packages/configurations/__init__.py", line 2, in <module>
    from .base import Settings, Configuration
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python2.7/site-packages/configurations/base.py", line 7, in <module>
    from .utils import uppercase_attributes
  File "/home/ncoghlan/.virtualenvs/warehouse/lib/python2.7/site-packages/configurations/utils.py", line 5, in <module>
    from django.utils.importlib import import_module
ImportError: No module named importlib
```

**Comment by dstufft** [comment]
I think you're installing Warehouse from PyPI which is a really old iteration of it or your branch is really old. Particularly confusing is there is no ``requirements.txt`` in the root directory anymore nor is there a ``warehouse init`` command anymore.

**Comment by dstufft** [comment]
Generally the supported way to run an environment now adays is via ``Docker``. You can run all the pieces on your own if you want, but it's easier to just do ``docker-compose build && docker-compose up``. See: https://warehouse.pypa.io/en/latest/development/getting-started/

**Comment by dstufft** [comment]
Note, that if you have an old clone of Warehouse, the new master branch is a wholly distinct orphan branch from the previous branches so you'd probably want to just blow away the old repository.

**Comment by ncoghlan** [comment]
Oh, I bet what happened is I had an old fork on *GitHub*, so even though the local clone was new, the fork was old.

**Comment by ncoghlan** [comment]
Yep, my fork is ancient, I just forgot about that because I'd only previously used it for online edits. Sorry for the noise.
