### ISSUE TITLE
Root cause Bandersnatch hitting Stale Cached JSON API Requests

### ISSUE THREAD

**Issue by cooperlees** [pypa/warehouse#4892]
**Describe the bug**
Summary: Bandersnatch installs hitting stale JSON API Data
Full Details: https://github.com/pypa/bandersnatch/issues/56
Purge Hack: https://github.com/pypa/bandersnatch/pull/57

**Expected behavior**
Bandersnatch not having to PURGE the cache.

**To Reproduce**
Unknown here, but I’d suggest lets add logging / collection of more data about Bandersnatch user-agent calling purges

**My Platform**
Bandersnatch with requests

**Comment by igotcha** [comment]
we have the same problem here:

2018-10-23 16:30:58,066 INFO: bandersnatch/3.0.0.dev0 (cpython 3.6.6-final0, Linux x86_64)
2018-10-23 16:30:58,123 INFO: Syncing with https://pypi.python.org.
2018-10-23 16:30:58,124 INFO: Current mirror serial: 4344762
2018-10-23 16:30:58,124 INFO: Resuming interrupted sync from local todo list.
2018-10-23 16:30:58,188 INFO: Trying to reach serial: 4346516
2018-10-23 16:30:58,188 INFO: 7 packages to sync.
2018-10-23 16:30:58,190 INFO: Syncing package: basetuyaapi (serial 4346273)
2018-10-23 16:30:58,191 INFO: Syncing package: disparitySMD (serial 4345765)
2018-10-23 16:30:58,192 INFO: Syncing package: nixcms (serial 4346344)
2018-10-23 16:31:00,187 INFO: disparitySMD no longer exists on PyPI
2018-10-23 16:31:00,187 INFO: Syncing package: pacifica-python-downloader (serial 4346407)
2018-10-23 16:31:00,260 INFO: basetuyaapi no longer exists on PyPI
2018-10-23 16:31:00,260 INFO: Syncing package: portus (serial 4345746)
2018-10-23 16:31:01,468 INFO: nixcms no longer exists on PyPI
2018-10-23 16:31:01,468 INFO: Syncing package: python-todict (serial 4346125)
2018-10-23 16:31:01,686 INFO: portus no longer exists on PyPI
2018-10-23 16:31:01,687 INFO: Syncing package: toil-ionox0 (serial 4346027)
2018-10-23 16:31:02,318 INFO: pacifica-python-downloader no longer exists on PyPI
2018-10-23 16:31:02,941 INFO: python-todict no longer exists on PyPI
2018-10-23 16:31:04,242 ERROR: Stale serial for package toil-ionox0 - Attempt 1
2018-10-23 16:31:05,243 INFO: Syncing package: toil-ionox0 (serial 4346027)
2018-10-23 16:31:08,199 ERROR: Stale serial for package toil-ionox0 - Attempt 2
2018-10-23 16:31:10,201 INFO: Syncing package: toil-ionox0 (serial 4346027)
2018-10-23 16:31:12,318 ERROR: Stale serial for package toil-ionox0 - Attempt 3
2018-10-23 16:31:12,318 ERROR: Stale serial for toil-ionox0 (4346027) not updating. Giving up.
2018-10-23 16:31:12,319 INFO: Generating global index page.

**Comment by ExplodingCabbage** [comment]
This issue became the topic of today's Daily WTF: https://thedailywtf.com/articles/it-s-a-little-stale

A commenter there bitched that this issue doesn't contain proper instructions on how to reproduce, while the Daily WTF article almost does and so is actually more useful as a bug report than this issue is. I don't understand everything here well enough to evaluate whether that's a fair comment, but thought I'd drop the link here anyway in case it's useful.

(Of course, since it's the Daily WTF, there's some risk that the key details of the story have been broken in an effort to anonymise or dramatise the story. I don't know whether "Megan K" and @cooperlees are the same person.)

**Comment by mailukas** [comment]
@ExplodingCabbage [pypa/bandersnatch#56](https://github.com/pypa/bandersnatch/issues/56) contains full details (more than the Daily WTF article).

**Comment by YMIndustries** [comment]
> @ExplodingCabbage [pypa/bandersnatch#56](https://github.com/pypa/bandersnatch/issues/56) contains full details (more than the Daily WTF article).

And that issue was posted by Megan K. Mystery solved.

**Comment by ExplodingCabbage** [comment]
I've nuked a previous comment of mine (referred to above by @mailukas and @YMIndustries) because, unbeknownst to me at the time that I posted it, it leaked some information that was meant to be private. If a repo maintainer comes along, I suggest they delete the two comments above by @mailukas's and @YMIndustries, and also this one. (@mailukas and @YMIndustries may also wish to delete their own comments.)

**Comment by di** [comment]
Another report of a stale cache: #5017.

**Comment by di** [comment]
Yet another: #5323.

**Comment by brainwane** [comment]
@cooperlees checking in since it's been a few months -- you said on the Bandersnatch issue

> Can we somehow get more logging about how often Bandersnatch is hitting this and then think about how from this we will try and debug why requests is hitting this

You mean logging from the Bandersnatch side or from the PyPI side?

**Comment by cooperlees** [comment]
From warehouse logs. We should be able to store where requests from the "bandersnatch" User-Agent hitting this endpoint are coming from and see if that helps work out why it's happening.

Bandersnatch logs stay out on individuals computers and we can not analyze them centrally like warehouse.

**Comment by cooperlees** [comment]
Does anyone have time for debugging this? Do we want to remove the hack in https://github.com/pypa/bandersnatch/pull/57 for Bandersnatch where it tries and clear stale caches.

**Comment by R1j1t** [comment]
Hi, I also have the same issue. I recently uploaded my first package to pypi but it is not appearning in search. I tried searching by name, no luck. Then i used license -> date last updated there are also I cannot find the package. I am assuming this is not an expected behaviors. Is there something, I am missing or something wrong with my upload?

Here is the link https://pypi.org/project/contextualSpellCheck/.

**Comment by cooperlees** [comment]
> Hi, I also have the same issue. I recently uploaded my first package to pypi but it is not appearning in search. I tried searching by name, no luck. Then i used license -> date last updated there are also I cannot find the package. I am assuming this is not an expected behaviors. Is there something, I am missing or something wrong with my upload?
> 
> Here is the link https://pypi.org/project/contextualSpellCheck/.

@R1j1t - I don't think your issue and this CDN stale cache issue are related ... This is forcing the CDN to refetch from origin.

I need to workout if this is still happening. Might try and add more verbose logging to bandersnatch around this and see if people notice.

**Comment by dstufft** [comment]
With https://github.com/pypi/warehouse/pull/13936 merged now (along with a few follow up PRs to fix some deadlocks), I *think* that the primary cause of this has been fixed now.

The tl;dr is that our mirroring relied on the serial to be a monotonically increasing integer, but due to the way PostgreSQL works, concurrent transactions could end up with serials being "out of order", and https://github.com/pypi/warehouse/pull/13936 changes that so that transactions that generate new serial numbers are serialized behind what is effectively a mutex.

I'm going to close this now, but if anyone sees any new reports of this happening after today, we can re-open this issue.

**Comment by cooperlees** [comment]
Wow. Thanks Donald. Will hola if anyone sees anything.

**Comment by jasom** [comment]
I'm seeing an exactly off-by-one error in serial occasionally bandersnatch 6.4.0 (I can upgrade to a newer bandersnatch if you think this is an error on the client side).  Here's my most recent log:

```
2025-05-01 19:15:10,751 INFO: Fetching metadata for package: pyagrum-nightly (serial 28819318) (package.py:58)
2025-05-01 19:15:10,770 ERROR: Stale serial for package pyagrum-nightly - Attempt 3 (package.py:76)
2025-05-01 19:15:10,770 ERROR: Stale serial for pyagrum-nightly (28819318) not updating. Giving up. (package.py:82)
2025-05-01 19:15:10,770 ERROR: Error syncing package: pyagrum-nightly@28819318 (mirror.py:385)
Traceback (most recent call last):
  File "/nix/store/572184cf5yc421j1lla6416r7ahgw7g7-python3.10-bandersnatch-6.4.0/lib/python3.10/site-packages/bandersnatch/package.py", line 61, in update_metadata
    self._metadata = await master.get_package_metadata(
  File "/nix/store/572184cf5yc421j1lla6416r7ahgw7g7-python3.10-bandersnatch-6.4.0/lib/python3.10/site-packages/bandersnatch/master.py", line 223, in get_package_metadata
    metadata_response = await metadata_generator.asend(None)
  File "/nix/store/572184cf5yc421j1lla6416r7ahgw7g7-python3.10-bandersnatch-6.4.0/lib/python3.10/site-packages/bandersnatch/master.py", line 139, in get
    await self.check_for_stale_cache(path, required_serial, got_serial)
  File "/nix/store/572184cf5yc421j1lla6416r7ahgw7g7-python3.10-bandersnatch-6.4.0/lib/python3.10/site-packages/bandersnatch/master.py", line 118, in check_for_stale_cache
    raise StalePage(
bandersnatch.master.StalePage: Expected PyPI serial 28819318 for request https://pypi.org/pypi/pyagrum-nightly/json but got 28819317. We can no longer issue a PURGE. Report issue to PyPA Warehouse GitHub if it persists ...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/572184cf5yc421j1lla6416r7ahgw7g7-python3.10-bandersnatch-6.4.0/lib/python3.10/site-packages/bandersnatch/mirror.py", line 131, in package_syncer
    await package.update_metadata(self.master, attempts=3)
  File "/nix/store/572184cf5yc421j1lla6416r7ahgw7g7-python3.10-bandersnatch-6.4.0/lib/python3.10/site-packages/bandersnatch/package.py", line 86, in update_metadata
    raise error_class(package_name=self.name, attempts=attempts)
bandersnatch.errors.StaleMetadata: Stale serial for pyagrum-nightly after 3 attempts
```

**Comment by cooperlees** [comment]
Interesting, if we prove it's a client issue, happy to take a PR / help debug.

**Comment by 89ao** [comment]
hi @dstufft @cooperlees , for the record ,We recently experienced a similar issue.(this time is boto3)

```
2025-06-28 07:51:00,733 bandersnatch.mirror: INFO 1 packages to sync.
2025-06-28 07:51:00,734 bandersnatch.mirror: INFO No metadata filters are enabled. Skipping metadata filtering
2025-06-28 07:51:00,734 bandersnatch.mirror: INFO No release file filters are enabled. Skipping release file filtering
2025-06-28 07:51:00,734 bandersnatch.package: INFO Fetching metadata for package: boto3 (serial 29854871)
2025-06-28 07:51:00,773 bandersnatch.package: ERROR Stale serial for package boto3 - Attempt 1
2025-06-28 07:51:01,774 bandersnatch.package: INFO Fetching metadata for package: boto3 (serial 29854871)
2025-06-28 07:51:01,812 bandersnatch.package: ERROR Stale serial for package boto3 - Attempt 2
2025-06-28 07:51:03,814 bandersnatch.package: INFO Fetching metadata for package: boto3 (serial 29854871)
2025-06-28 07:51:03,843 bandersnatch.package: ERROR Stale serial for package boto3 - Attempt 3
2025-06-28 07:51:03,843 bandersnatch.package: ERROR Stale serial for boto3 (29854871) not updating. Giving up.
2025-06-28 07:51:03,844 bandersnatch.mirror: ERROR Error syncing package: boto3@29854871
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/package.py", line 61, in update_metadata
    self._metadata = await master.get_package_metadata(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/master.py", line 223, in get_package_metadata
    metadata_response = await metadata_generator.asend(None)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/master.py", line 141, in get
    await self.check_for_stale_cache(path, required_serial, got_serial)
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/master.py", line 120, in check_for_stale_cache
    raise StalePage(
bandersnatch.master.StalePage: Expected PyPI serial 29854871 for request https://pypi.org/pypi/boto3/json but got 29854870. We can no longer issue a PURGE. Report issue to PyPA Warehouse GitHub if it persists ...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/mirror.py", line 129, in package_syncer
    await package.update_metadata(self.master, attempts=3)
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/package.py", line 86, in update_metadata
    raise error_class(package_name=self.name, attempts=attempts)
bandersnatch.errors.StaleMetadata: Stale serial for boto3 after 3 attempts
2025-06-28 07:51:03,845 bandersnatch.simple: INFO Generating global index page.
2025-06-28 07:51:09,079 bandersnatch.mirror: INFO 0 packages had changes
```

**Comment by 89ao** [comment]
@dstufft @cooperlees again this time stuck with the ddtrace package.
```
2025-07-04 08:31:02,574 bandersnatch: INFO Initialized project plugin blocklist_project, filtering ['uselesscapitalquiz']
2025-07-04 08:31:02,575 bandersnatch: INFO Initialized regex release plugin with [re.compile('.+-nightly(-|$)')]
2025-07-04 08:31:02,584 bandersnatch: INFO Initialized prerelease plugin with [re.compile('.+rc\\d+$'), re.compile('.+a(lpha)?\\d+$'), re.compile('.+b(eta)?\\d+$'), re.compile('.+dev\\d+$')]
2025-07-04 08:31:02,584 bandersnatch: INFO Initialized prerelease plugin prerelease_release, filtering all packages
2025-07-04 08:31:02,586 bandersnatch.mirror: INFO Syncing with https://pypi.org.
2025-07-04 08:31:02,586 bandersnatch.mirror: INFO Current mirror serial: 29965778
2025-07-04 08:31:02,587 bandersnatch.mirror: INFO Resuming interrupted sync from local todo list.
2025-07-04 08:31:02,587 bandersnatch.mirror: INFO Trying to reach serial: 29966054
2025-07-04 08:31:02,587 bandersnatch.mirror: INFO 1 packages to sync.
2025-07-04 08:31:02,587 bandersnatch.mirror: INFO No metadata filters are enabled. Skipping metadata filtering
2025-07-04 08:31:02,587 bandersnatch.mirror: INFO No release file filters are enabled. Skipping release file filtering
2025-07-04 08:31:02,587 bandersnatch.package: INFO Fetching metadata for package: ddtrace (serial 29965814)
2025-07-04 08:31:02,711 bandersnatch.package: ERROR Stale serial for package ddtrace - Attempt 1
2025-07-04 08:31:03,713 bandersnatch.package: INFO Fetching metadata for package: ddtrace (serial 29965814)
2025-07-04 08:31:03,832 bandersnatch.package: ERROR Stale serial for package ddtrace - Attempt 2
2025-07-04 08:31:05,835 bandersnatch.package: INFO Fetching metadata for package: ddtrace (serial 29965814)
2025-07-04 08:31:05,951 bandersnatch.package: ERROR Stale serial for package ddtrace - Attempt 3
2025-07-04 08:31:05,951 bandersnatch.package: ERROR Stale serial for ddtrace (29965814) not updating. Giving up.
2025-07-04 08:31:05,951 bandersnatch.mirror: ERROR Error syncing package: ddtrace@29965814
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/package.py", line 61, in update_metadata
    self._metadata = await master.get_package_metadata(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/master.py", line 223, in get_package_metadata
    metadata_response = await metadata_generator.asend(None)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/master.py", line 141, in get
    await self.check_for_stale_cache(path, required_serial, got_serial)
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/master.py", line 120, in check_for_stale_cache
    raise StalePage(
bandersnatch.master.StalePage: Expected PyPI serial 29965814 for request https://pypi.org/pypi/ddtrace/json but got 29965813. We can no longer issue a PURGE. Report issue to PyPA Warehouse GitHub if it persists ...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/mirror.py", line 129, in package_syncer
    await package.update_metadata(self.master, attempts=3)
  File "/usr/local/lib/python3.12/site-packages/bandersnatch/package.py", line 86, in update_metadata
    raise error_class(package_name=self.name, attempts=attempts)
bandersnatch.errors.StaleMetadata: Stale serial for ddtrace after 3 attempts
2025-07-04 08:31:05,953 bandersnatch.simple: INFO Generating global index page.
2025-07-04 08:31:07,176 bandersnatch.mirror: INFO 0 packages had changes
```
