### ISSUE TITLE
While installing PasteScript 1.7.5, getting dependencies error(Searching for setuptools-scm>=1.15.0)

### ISSUE THREAD

**Issue by mukul3062** [pypa/warehouse#5056]
**Describe the bug**

./usr/bin/python setup.py bdist_egg -vvvvv
running bdist_egg
running egg_info
Searching for PasteDeploy
Best match: PasteDeploy 1.5.2
Processing PasteDeploy-1.5.2-py2.7.egg

Using dir/downloads/dist/PasteScript-1.7.5/.eggs/PasteDeploy-1.5.2-py2.7.egg
Searching for Paste==3.0.3
Reading https://pypi.python.org/simple/Paste/
Best match: Paste 3.0.3
Downloading https://files.pythonhosted.org/packages/7a/3e/b6330b5d34875cc58192b94acbe4405658ae6567ea53f382a0fcde25785e/Paste-3.0.3.tar.gz#sha256=96b06ff055c4f22a4e5c164551179ed1fa8263bc3ce69b4347c617cd0fcf51f4
Processing Paste-3.0.3.tar.gz
Writing /tmp/easy_install-p66UB9/Paste-3.0.3/setup.cfg
Running Paste-3.0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-p66UB9/Paste-3.0.3/egg-dist-tmp-eBZUKB
Searching for pytest-runner
Reading https://pypi.python.org/simple/pytest-runner/
Best match: pytest-runner 4.2
Downloading https://files.pythonhosted.org/packages/9e/b7/fe6e8f87f9a756fd06722216f1b6698ccba4d269eac6329d9f0c441d0f93/pytest-runner-4.2.tar.gz#sha256=d23f117be39919f00dd91bffeb4f15e031ec797501b717a245e377aee0f577be
Processing pytest-runner-4.2.tar.gz
Writing /tmp/easy_install-p66UB9/Paste-3.0.3/temp/easy_install-ZGLs9b/pytest-runner-4.2/setup.cfg
Running pytest-runner-4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-p66UB9/Paste-3.0.3/temp/easy_install-ZGLs9b/pytest-runner-4.2/egg-dist-tmp-Id8SLi
Searching for setuptools-scm>=1.15.0
Reading https://pypi.python.org/simple/setuptools_scm/
Best match: setuptools-scm 3.1.0
Downloading https://files.pythonhosted.org/packages/fd/a8/d60c50c6a729342534501530f57a8a1743d52c2877814dfced5575a2e035/setuptools_scm-3.1.0-py2.7.egg#sha256=14db63c379b69393e9581df438e761b10d2d4060ae81b22a910d87751c0dc15a
Processing setuptools_scm-3.1.0-py2.7.egg
Moving setuptools_scm-3.1.0-py2.7.egg to /tmp/easy_install-p66UB9/Paste-3.0.3/temp/easy_install-ZGLs9b/pytest-runner-4.2/.eggs

Installed /tmp/easy_install-p66UB9/Paste-3.0.3/temp/easy_install-ZGLs9b/pytest-runner-4.2/.eggs/setuptools_scm-3.1.0-py2.7.egg
dir/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
Traceback (most recent call last):
  File "setup.py", line 145, in <module>
    'PasteDeploy',
  File "dir/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "dir/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "dir/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/bdist_egg.py", line 152, in run
  File "dir/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "dir/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 160, in run
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2182, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2196, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 618, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 870, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 882, in obtain
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 355, in fetch_build_egg
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 613, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 643, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 833, in install_eggs
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1055, in build_and_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1040, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 68, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 114, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 67, in runner
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 43, in _execfile
  File "/tmp/easy_install-p66UB9/Paste-3.0.3/setup.py", line 111, in <module>
    cherrypy=paste.script.cherrypy_server:cpwsgi_server
  File "dir/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 263, in __init__
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 288, in fetch_build_eggs
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 618, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 870, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 882, in obtain
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 355, in fetch_build_egg
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 613, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 643, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 833, in install_eggs
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1055, in build_and_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1040, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 68, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 114, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 67, in runner
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 43, in _execfile
  File "/tmp/easy_install-p66UB9/Paste-3.0.3/temp/easy_install-ZGLs9b/pytest-runner-4.2/setup.py", line 76, in <module>
    'Cheetah': ['Cheetah'],
  File "dir/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 267, in __init__
  File "dir/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 302, in finalize_options
  File "/tmp/easy_install-p66UB9/Paste-3.0.3/temp/easy_install-ZGLs9b/pytest-runner-4.2/.eggs/setuptools_scm-3.1.0-py2.7.egg/setuptools_scm/integration.py", line 10, in version_keyword
  File "/tmp/easy_install-p66UB9/Paste-3.0.3/temp/easy_install-ZGLs9b/pytest-runner-4.2/.eggs/setuptools_scm-3.1.0-py2.7.egg/setuptools_scm/version.py", line 66, in _warn_if_setuptools_outdated
setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)

**Expected behavior**

PasteScript should get installed without any issues, this issues starts coming after "Paste-3.0.3" version pushed in pypi on 3rd Nov, 2018

**To Reproduce**

Create egg from PasteScript  tar file using below coommand
./usr/bin/python setup.py bdist_egg -vvvvv

**My Platform**

Linux Centos7
Python 2.7.12
Setuptools 5.7

**Additional context**

**Comment by ewdurbin** [comment]
Hi @mukul3062! This issue tracker is for issues related to the codebase that runs pypi.org itself, not the projects hosted there.

You issue should likely be filed at https://bitbucket.org/ianb/pastescript/issues?status=new&status=open, but I do note that the error message is helpful:

>>> setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)

You may want to update `setuptools` and see if that resolves your problem.
