### ISSUE TITLE
Can't get get_user_entered_format() to work

### ISSUE THREAD

**Issue by ArielS1** [pypa/warehouse#6390]
I'm trying to find out a specific cell's color like this:
`format = get_user_entered_format(worksheet, "R2C1")`

and i get the following exception:
`Traceback (most recent call last):
  File ".\script.py", line 25, in <module>
    parser()
  File ".\script.py", line 23, in script
    format = get_user_entered_format(worksheet, "R2C1")
  File "C:\Python37\lib\site-packages\gspread_formatting.py", line 89, in get_user_entered_format
    props = resp['sheets'][0]['data'][0]['rowData'][0]['values'][0].get('userEnteredFormat')
KeyError: 'rowData'`

the worksheet is a valid worksheet generated by gc.open_by_url('https://..').sheet1
and the cell exists and has a background color

**Comment by ArielS1** [comment]
wrong project :-)
