### ISSUE TITLE
Missing translation strings in Weblate

### ISSUE THREAD

**Issue by webknjaz** [pypa/warehouse#6850]
## Bad source in Weblate

There's parts of the website that aren't present in Weblate. I guess that's because they were marked translatable after the initial upload.
So we need to collect new strings and sync them there.

![photo5278686657471687796](https://user-images.githubusercontent.com/578543/66927874-dbe7aa80-f030-11e9-82f0-cc03738b9bc7.jpg)

**Comment by webknjaz** [comment]
P.S. I checked that those places appear in English in other locales as well.

**Comment by ewdurbin** [comment]
It appears that `{% trans %}` tags for the template these source from are not being picked up despite being inspected while compiling the pot...

```
$ make compile-pot
/Users/ewdurbin/ernestd/warehouse/.state/env/bin/pybabel extract \
	-F babel.cfg \
	--copyright-holder="PyPA" \
	--msgid-bugs-address="https://github.com/pypa/warehouse/issues/new" \
	--project="Warehouse" \
	--output="warehouse/locale/messages.pot" \
	warehouse
extracting messages from warehouse/__init__.py
extracting messages from warehouse/__main__.py
**snip**
extracting messages from warehouse/templates/packaging/detail.html (encoding="utf-8", extensions="jinja2.ext.autoescape,jinja2.ext.with_")
**snip**
extracting messages from warehouse/utils/db/__init__.py
extracting messages from warehouse/utils/db/windowed_query.py
writing PO template file to warehouse/locale/messages.pot
$ grep 'warehouse/templates/packaging/detail.html' warehouse/locale/messages.pot 
$ 
```

**Comment by ewdurbin** [comment]
that's curious...

```
$ .state/env/bin/pybabel extract -F babel.cfg warehouse/templates/packaging/detail.html --output /dev/stdout
extracting messages from warehouse/templates/packaging/detail.html (encoding="utf-8", extensions="jinja2.ext.autoescape,jinja2.ext.with_")
writing PO template file to /dev/stdout
# Translations template for PROJECT.
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2019-10-16 10:37-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.7.0\n"

$ 
```

**Comment by ewdurbin** [comment]
Unfortunately simply adding the extension to `babel.cfg` doesn't quite work due to pathing:

```diff
diff --git a/babel.cfg b/babel.cfg
index ff712083..7a3f4461 100644
--- a/babel.cfg
+++ b/babel.cfg
@@ -1,4 +1,4 @@
 [python: **.py]
 [jinja2: **.html]
 encoding = utf-8
-extensions=jinja2.ext.autoescape,jinja2.ext.with_
+extensions=jinja2.ext.autoescape,jinja2.ext.with_,warehouse.utils.html.ClientSideIncludeExtension
```

```shell
$ make compile-pot
/Users/ewdurbin/ernestd/warehouse/.state/env/bin/pybabel extract \
	-F babel.cfg \
	--copyright-holder="PyPA" \
	--msgid-bugs-address="https://github.com/pypa/warehouse/issues/new" \
	--project="Warehouse" \
	--output="warehouse/locale/messages.pot" \
	warehouse
extracting messages from warehouse/__init__.py
**snip**
extracting messages from warehouse/admin/squats.py
extracting messages from warehouse/admin/templates/admin/base.html (encoding="utf-8", extensions="jinja2.ext.autoescape,jinja2.ext.with_,warehouse.utils.html.ClientSideIncludeExtension")
Traceback (most recent call last):
  File "/Users/ewdurbin/ernestd/warehouse/.state/env/bin/pybabel", line 8, in <module>
    sys.exit(main())
  File "/Users/ewdurbin/ernestd/warehouse/.state/env/lib/python3.7/site-packages/babel/messages/frontend.py", line 929, in main
    return CommandLineInterface().run(sys.argv)
  File "/Users/ewdurbin/ernestd/warehouse/.state/env/lib/python3.7/site-packages/babel/messages/frontend.py", line 853, in run
    return cmdinst.run()
  File "/Users/ewdurbin/ernestd/warehouse/.state/env/lib/python3.7/site-packages/babel/messages/frontend.py", line 481, in run
    for filename, lineno, message, comments, context in extracted:
  File "/Users/ewdurbin/ernestd/warehouse/.state/env/lib/python3.7/site-packages/babel/messages/extract.py", line 157, in extract_from_dir
    dirpath=absname,
  File "/Users/ewdurbin/ernestd/warehouse/.state/env/lib/python3.7/site-packages/babel/messages/extract.py", line 212, in check_and_call_extract_file
    strip_comment_tags=strip_comment_tags
  File "/Users/ewdurbin/ernestd/warehouse/.state/env/lib/python3.7/site-packages/babel/messages/extract.py", line 241, in extract_from_file
    strip_comment_tags))
  File "/Users/ewdurbin/ernestd/warehouse/.state/env/lib/python3.7/site-packages/babel/messages/extract.py", line 322, in extract
    for lineno, funcname, messages, comments in results:
  File "/Users/ewdurbin/ernestd/warehouse/.state/env/lib/python3.7/site-packages/jinja2/ext.py", line 575, in babel_extract
    extensions.add(import_string(extension))
  File "/Users/ewdurbin/ernestd/warehouse/.state/env/lib/python3.7/site-packages/jinja2/utils.py", line 143, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
ModuleNotFoundError: No module named 'warehouse'
make: *** [Makefile:178: compile-pot] Error 1
```

**Comment by webknjaz** [comment]
I've bisected it to 
https://github.com/pypa/warehouse/blob/bc6a10b/warehouse/templates/packaging/detail.html#L130-L142

Removing this block makes babel work.

**Comment by ewdurbin** [comment]
We need to configure pybabel to load the extension like so:

```diff
diff --git a/babel.cfg b/babel.cfg
index ff712083..7a3f4461 100644
--- a/babel.cfg
+++ b/babel.cfg
@@ -1,4 +1,4 @@
 [python: **.py]
 [jinja2: **.html]
 encoding = utf-8
-extensions=jinja2.ext.autoescape,jinja2.ext.with_
+extensions=jinja2.ext.autoescape,jinja2.ext.with_,warehouse.utils.html.ClientSideIncludeExtension
```

And then we need to figure out how to get the module into the search path when running pybabel... I don't have time right now to work on this though.

**Comment by ewdurbin** [comment]
Just to confirm:

```
$ ln -s $(pwd)/warehouse .state/env/lib/python3.7/site-packages/warehouse
$ make compile-pot
/Users/ewdurbin/ernestd/warehouse/.state/env/bin/pybabel extract \
	-F babel.cfg \
	--copyright-holder="PyPA" \
	--msgid-bugs-address="https://github.com/pypa/warehouse/issues/new" \
	--project="Warehouse" \
	--output="warehouse/locale/messages.pot" \
	warehouse
extracting messages from warehouse/__init__.py
**snip**
extracting messages from warehouse/templates/packaging/detail.html (encoding="utf-8", extensions="jinja2.ext.autoescape,jinja2.ext.with_,warehouse.utils.html.ClientSideIncludeExtension")
**snip**
extracting messages from warehouse/utils/db/windowed_query.py
writing PO template file to warehouse/locale/messages.pot
$ grep 'packaging/detail.html' warehouse/locale/messages.pot 
#: warehouse/templates/packaging/detail.html:279
**snip**
#: warehouse/templates/packaging/detail.html:321
$ 
```

**Comment by webknjaz** [comment]
search path? as in `PYTHONPATH=`?

**Comment by webknjaz** [comment]
As a workaround, I could send a PR updating the POT file with a local hack...

**Comment by ewdurbin** [comment]
I think we should resolve this issue to ensure messages.pot stays up to date.

**Comment by webknjaz** [comment]
Also, it would be nice to add some sanity test/linter checking that parsing templates doesn't give an empty result.

**Comment by ewdurbin** [comment]
> Also, it would be nice to add some sanity test/linter checking that parsing templates doesn't give an empty result.

Yes, we should: #6851
