### ISSUE TITLE
getting this error when trying to install bpy

### ISSUE THREAD

**Issue by Chhayank-Sharma** [pypa/warehouse#7104]
C:\Users\Hamender Kumar>pip install bpy==1.2.2
Collecting bpy==1.2.2
  Downloading https://files.pythonhosted.org/packages/92/86/de6e0d9e57fcdac81089f4fb8cebc8e17f62718d2b26e57fade5fe344055/bpy-1.2.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hamender kumar\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hamender Kumar\\AppData\\Local\\Temp\\pip-install-z8dzem3t\\bpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hamender Kumar\\AppData\\Local\\Temp\\pip-install-z8dzem3t\\bpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Hamender Kumar\AppData\Local\Temp\pip-install-z8dzem3t\bpy\pip-egg-info'
         cwd: C:\Users\Hamender Kumar\AppData\Local\Temp\pip-install-z8dzem3t\bpy\
    Complete output (164 lines):
    Traceback (most recent call last):
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
        self.run_command(cmdname)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
        self.build()
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\command\install_lib.py", line 105, in build
        self.run_command('build_py')
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\build_py.py", line 52, in run
        self.build_packages()
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\command\build_py.py", line 372, in build_packages
        self.build_module(module, module_file, package)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\build_py.py", line 74, in build_module
        outfile, copied = orig.build_py.build_module(self, module, module_file,
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\command\build_py.py", line 342, in build_module
        self.mkpath(dir)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 338, in mkpath
        dir_util.mkpath(name, mode, dry_run=self.dry_run)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\dir_util.py", line 70, in mkpath
        os.mkdir(head, mode)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 310, in wrap
        path = self._remap_input(name, path, *args, **kw)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 452, in _remap_input
        self._violation(operation, os.path.realpath(path), *args, **kw)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 407, in _violation
        raise SandboxViolation(operation, args, kw)
    setuptools.sandbox.SandboxViolation: SandboxViolation: mkdir('C:\\Users\\HAMEND~1\\AppData\\Local\\Temp\\easy_install-48niitrn\\svn-0.3.46\\build', 511) {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\HAMEND~1\AppData\Local\Temp\easy_install-48niitrn\svn-0.3.46\setup.py", line 14, in <module>
        import sys
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: SandboxViolation: mkdir('C:\\Users\\HAMEND~1\\AppData\\Local\\Temp\\easy_install-48niitrn\\svn-0.3.46\\build', 511) {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\HAMEND~1\AppData\Local\Temp\easy_install-48niitrn\svn-0.3.46\setup.py", line 14, in <module>
        import sys
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: SandboxViolation: mkdir('C:\\Users\\HAMEND~1\\AppData\\Local\\Temp\\easy_install-48niitrn\\svn-0.3.46\\build', 511) {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Hamender Kumar\AppData\Local\Temp\pip-install-z8dzem3t\bpy\setup.py", line 404, in <module>
        setup(name='bpy',
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\users\hamender kumar\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('C:\\Users\\HAMEND~1\\AppData\\Local\\Temp\\easy_install-48niitrn\\svn-0.3.46\\build', 511) {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

**Comment by jamadden** [comment]
Thanks for the report, but this isn't the place for it. This tracker is only for issues with the software that runs pypi.org itself. It cannot help with packages distributed from there. You'll need to contact the maintainers of the package you're trying to install. 

Based on the project page at https://pypi.org/project/bpy/ you can contact them at https://github.com/TylerGubala/blenderpy
