### ISSUE TITLE
text to speech blocked

### ISSUE THREAD

**Issue by BL4CKID** [pypa/warehouse#7180]
2020-01-04T09:50:34.801080+00:00 app[worker.1]: gtts.tts.gTTSError: Failed to connect. Probable cause: Host 'https://translate.google.id/' is not reachable
2020-01-04T09:50:34.801082+00:00 app[worker.1]: 
2020-01-04T09:50:34.801083+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2020-01-04T09:50:34.801084+00:00 app[worker.1]: 
2020-01-04T09:50:34.801086+00:00 app[worker.1]: Traceback (most recent call last):
2020-01-04T09:50:34.801093+00:00 app[worker.1]:   File "/usr/lib/python3.8/site-packages/telethon/client/updates.py", line 428, in _dispatch_update
2020-01-04T09:50:34.801094+00:00 app[worker.1]:     await callback(event)
2020-01-04T09:50:34.801096+00:00 app[worker.1]:   File "/root/userbot/userbot/events.py", line 131, in wrapper
2020-01-04T09:50:34.801097+00:00 app[worker.1]:     await check.client.respond(
2020-01-04T09:50:34.801099+00:00 app[worker.1]: AttributeError: 'TelegramClient' object has no attribute 'respond'

**Comment by BL4CKID** [comment]
I think it should be .translate.google.co.<ltd> if

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with software installed from there (for example, using `pip install <SOME PACKAGE>`). You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page (`https://pypi.org/project/<SOME PACKAGE>`).
