### ISSUE TITLE
Connection reset by peer on pip install during Google Cloud Build process

### ISSUE THREAD

**Issue by thinkjrs** [pypa/warehouse#7303]
Though this seems to occur randomly, and is just occurring for me today, it appears that I am experiencing something related to issue #3826, wherein @di  suggests to file a new issue. 

This is not happening with extreme frequency (three times today out of 30 or so builds), but 10% is enough to suggest something's possibly awry.
 
My build seems to fail when downloading the `SQLAlchemy` package. 

Traceback:
```
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
raise ProtocolError("Connection broken: %r" % e, e)
File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
self.gen.throw(type, value, traceback)
File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
data = self.read(amt=amt, decode_content=decode_content)
File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
decode_content=False,
File "/usr/local/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 39, in response_chunks
for x in it:
File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 160, in iter
for chunk in download.chunks:
File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 303, in _download_http_url
link, downloader, temp_dir.path, hashes
File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 159, in unpack_http_url
hashes=hashes,
File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 287, in unpack_url
hashes=hashes,
File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
abstract_dist = self.preparer.prepare_linked_requirement(req)
File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
abstract_dist = self._get_abstract_dist_for(req_to_install)
File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
discovered_reqs.extend(self._resolve_one(requirement_set, req))
File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
resolver.resolve(requirement_set)
File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
status = self.run(options, args)
File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

ConnectionResetError: [Errno 104] Connection reset by peer
return self._sslobj.read(len, buffer)
File "/usr/local/lib/python3.7/ssl.py", line 929, in read
return self.read(nbytes, buffer)
File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
return self._sock.recv_into(b)
File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
n = self.fp.readinto(b)
File "/usr/local/lib/python3.7/http/client.py", line 501, in readinto
n = self.readinto(b)
File "/usr/local/lib/python3.7/http/client.py", line 457, in read
data = self.__fp.read(amt)
File "/usr/local/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
data = self._fp.read(amt) if not fp_closed else b""
File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
yield
File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
Traceback (most recent call last):
ERROR: Exception:
Downloading SQLAlchemy-1.3.13.tar.gz (6.0 MB)
Collecting sqlalchemy==1.3.13
```

**Comment by di** [comment]
Hi @thinkjrs, are you still experiencing this? Are you able to try increasing the timeout for `pip`?

```
pip install --default-timeout=1000 ...
```
