### ISSUE TITLE
HTTPError: 504 Server Error: Gateway Time-out for url: https://upload.pypi.org/legacy/

### ISSUE THREAD

**Issue by kroitor** [pypa/warehouse#7642]
Hi!

When trying to upload a built package with twine to pypi it reports the following:

```
removing build/bdist.linux-x86_64/wheel
Uploading distributions to https://upload.pypi.org/legacy/
Uploading ccxt-1.25.2-py2.py3-none-any.whl

  0%|          | 0.00/1.55M [00:00<?, ?B/s]
  1%|          | 8.00k/1.55M [00:00<00:21, 75.1kB/s]
 67%|######7   | 1.04M/1.55M [00:00<00:05, 107kB/s] 
100%|##########| 1.55M/1.55M [00:05<00:00, 308kB/s]
Received "504: Gateway Time-out" Package upload appears to have failed.  Retry 1 of 5
Uploading ccxt-1.25.2-py2.py3-none-any.whl

  0%|          | 0.00/1.55M [00:00<?, ?B/s]
 89%|########8 | 1.38M/1.55M [00:00<00:00, 12.1MB/s]
100%|##########| 1.55M/1.55M [00:10<00:00, 152kB/s] 
Received "504: GATEWAY_TIMEOUT" Package upload appears to have failed.  Retry 2 of 5
Uploading ccxt-1.25.2-py2.py3-none-any.whl

  0%|          | 0.00/1.55M [00:00<?, ?B/s]
100%|##########| 1.55M/1.55M [00:01<00:00, 1.34MB/s]
Received "502: Bad Gateway" Package upload appears to have failed.  Retry 3 of 5
Uploading ccxt-1.25.2-py2.py3-none-any.whl

  0%|          | 0.00/1.55M [00:00<?, ?B/s]
100%|##########| 1.55M/1.55M [00:05<00:00, 317kB/s]
Received "504: Gateway Time-out" Package upload appears to have failed.  Retry 4 of 5
Uploading ccxt-1.25.2-py2.py3-none-any.whl

  0%|          | 0.00/1.55M [00:00<?, ?B/s]
100%|##########| 1.55M/1.55M [00:05<00:00, 314kB/s]
Received "504: Gateway Time-out" Package upload appears to have failed.  Retry 5 of 5
NOTE: Try --verbose to see response content.
HTTPError: 504 Server Error: Gateway Time-out for url: https://upload.pypi.org/legacy/
```

I may be not the only one having this issue right now. 

Please see the tail of the build log attached below, at the end of it where it is trying to upload the built+tested package to PyPI using the default URL.

I'm using my regular credentials to push it, and it was working 12 hours ago:

```
python setup.py sdist bdist_wheel
twine upload dist/* -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}
```

The log is available here:

- https://api.travis-ci.org/v3/job/667140939/log.txt

Can anyone help on this issue, or confirm it or shed some light on it? 

I would assume it's a temporary networking glitch or something like that. But it makes impossible for me to upload package builds to PyPI now.

All help would be very much appreciated.

P.S. Pardon if this is not the right place to ask this type of questions (please, point the directions then).

**Comment by dmerejkowsky** [comment]
Search is broken to:

```
$ pip search sphinx
ERROR: HTTP error 503 while getting https://pypi.org/pypi
ERROR: Exception:
Traceback (most recent call last):
  File "/home/dmerej/.local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/dmerej/.local/lib/python3.7/site-packages/pip/_internal/commands/search.py", line 52, in run
    pypi_hits = self.search(query, options)
  File "/home/dmerej/.local/lib/python3.7/site-packages/pip/_internal/commands/search.py", line 71, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/home/dmerej/.local/lib/python3.7/site-packages/pip/_internal/network/xmlrpc.py", line 36, in request
    response.raise_for_status()
  File "/home/dmerej/.local/lib/python3.7/site-packages/pip/_vendor/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
pip._vendor.requests.exceptions.HTTPError: 503 Server Error: Backend is unhealthy for url: https://pypi.org/pypi
```

**Comment by jamadden** [comment]
Thanks for the reports! The admins and moderators are aware. In the interest of centralizing things, I'm going to close this in favor of #7643; please feel free to subscribe to that issue or follow 'pypi' and 'pythonstatus' on twitter.
