### ISSUE TITLE
 "[WinError 126] The specified module could not be found" when I execute plaidml-setup

### ISSUE THREAD

**Issue by iicedream** [pypa/warehouse#7813]
Hello everyone, I used the anaconda to pip plaidml-keras. I can pip successful,but when I execute the plaidml-setup, I got this error.
 
(kerasgpu) C:\Users\***>plaidml-setup
Traceback (most recent call last):
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\site-packages\plaidml\__init__.py", line 154, in load_library
    return ctypes.cdll.LoadLibrary(libpath)
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\ProgramData\Anaconda3\envs\kerasgpu\Scripts\plaidml-setup.exe\__main__.py", line 7, in <module>
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\site-packages\plaidml\plaidml_setup.py", line 16, in main
    ctx = plaidml.Context()
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\site-packages\plaidml\__init__.py", line 892, in Context
    return plaidml.context.Context(_lib())
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\site-packages\plaidml\__init__.py", line 789, in _lib
    _impl_lib = _Library()
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\site-packages\plaidml\__init__.py", line 176, in __init__
    lib = load_library('plaidml.dll', ['Library', 'bin'])
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\site-packages\plaidml\__init__.py", line 166, in load_library
    return ctypes.cdll.LoadLibrary(libpath)
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "e:\programdata\anaconda3\envs\kerasgpu\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found.

I'm not sure it has anything to do with that the version of my python is 3.7 and tensorflow=1.41,and my keras =2.2.4.
thanks for your answer

**Comment by iicedream** [comment]
I try many answers about this issue,including this answer: https://github.com/openslide/openslide-winbuild/issues/18 though is not quite much.

**Comment by jamadden** [comment]
Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with software installed from there (for example, using `pip install <SOME PACKAGE>`). You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page (`https://pypi.org/project/<SOME PACKAGE>`).

**Comment by iicedream** [comment]
ok,may be I should try more.Thanks for your answer.

**Comment by iicedream** [comment]
> Thanks for the report! Unfortunately, this is not the correct place for it. This tracker is only for issues with the software that runs https://pypi.org itself. It cannot help with software installed from there (for example, using `pip install <SOME PACKAGE>`). You'll need to contact the maintainers of that software instead. This contact information can often be found on the PyPI project page (`https://pypi.org/project/<SOME PACKAGE>`).

ok,may be I should try more.Thanks for your answer.
