### ISSUE TITLE
twine upload fails with HTTP 104 Connection reset by peer

### ISSUE THREAD

**Issue by mbarkhau** [pypa/warehouse#7848]
**Describe the bug**

I am trying to upload a new release but get an error. The most recent release worked fine two days ago and used the exact same project setup and virtual environment, but now I get this:

```
mbarkhau@mb-thinkpad:~/workspace/markdown-katex (master) (markdown-katex_py37)
$ ls -lh dist/*
-rw-r--r-- 1 mbarkhau mbarkhau 38M Apr 23 23:23 dist/markdown_katex-202004.15b0-py2.py3-none-any.whl
$ twine check dist/markdown_katex-202004.15b0-py2.py3-none-any.whl
Checking dist/markdown_katex-202004.15b0-py2.py3-none-any.whl: PASSED
mbarkhau@mb-thinkpad:~/workspace/markdown-katex (master) (markdown-katex_py37)
$ twine upload --verbose --skip-existing dist/markdown_katex-202004.15b0-py2.py3-none-any.whl
Uploading distributions to https://pypi.org
Uploading markdown_katex-202004.15b0-py2.py3-none-any.whl
  3%|██████▌                                                                                               | 1.02M/37.3M [00:00<00:14, 2.61MB/s]
Traceback (most recent call last):
  File "/home/mbarkhau/miniconda3/envs/markdown-katex_py37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/mbarkhau/miniconda3/envs/markdown-katex_py37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/mbarkhau/miniconda3/envs/markdown-katex_py37/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/mbarkhau/miniconda3/envs/markdown-katex_py37/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/mbarkhau/miniconda3/envs/markdown-katex_py37/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/mbarkhau/miniconda3/envs/markdown-katex_py37/lib/python3.7/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/home/mbarkhau/miniconda3/envs/markdown-katex_py37/lib/python3.7/http/client.py", line 987, in send
    self.sock.sendall(data)
  File "/home/mbarkhau/miniconda3/envs/markdown-katex_py37/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/home/mbarkhau/miniconda3/envs/markdown-katex_py37/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**My Platform**

```
mbarkhau@mb-thinkpad:~/workspace/markdown-katex (master) (markdown-katex_py37)
$ twine --version
twine version 3.1.1 (pkginfo: 1.5.0.1, requests: 2.23.0, setuptools:
46.1.3.post20200325, requests-toolbelt: 0.9.1, tqdm: 4.45.0)
$ python --version
Python 3.7.6
$ uname -a
Linux mb-thinkpad 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**

Connection to pypi.org seems to work in general:

```
$ pip install --no-cache-dir -U flask
Collecting flask
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 1.9 MB/s
Requirement already satisfied, skipping upgrade: Werkzeug>=0.15 in ...
Installing collected packages: flask
Successfully installed flask-1.1.2
```

**Comment by di** [comment]
Hi @mbarkhau, are you still having issues here?

**Comment by mbarkhau** [comment]
@di I just checked a moment ago and yes I still get the same error.

**Comment by di** [comment]
@mbarkhau Can you file a [Network Access Issue](https://github.com/pypa/pypi-support/issues/new?labels=network&template=access-issues.md) instead and include the above details as well?

**Comment by mbarkhau** [comment]
I managed to get it to work by setting the `--registry-url` like this:

```shell
twine upload --skip-existing \
        --repository-url https://upload.pypi.org/legacy/ \
        $(ls -1t dist/*.tar.gz | head -n 1) $(ls -1t dist/*.whl | head -n 1);
```
