### ISSUE TITLE
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

### ISSUE THREAD

**Issue by mahendra1999** [pypa/warehouse#8120]
In my setup

pip install websocket_client
Windows system
Pycharm
python 3.6

I pasted sample code i used for websocket connection

from websocket import create_connection

ws = create_connection('wss://cloud-stg.xyz.com/sockjs/8/****/websocket')
result = ws.recv()
print('Result: {}'.format(result))

result = ws.recv()
print('Result: {}'.format(result))

ws.send(json.dumps([json.dumps({'msg': 'connect', 'version': '1', 'support': ['1', 'pre2', 'pre1']})]))
result = ws.recv()
result = ws.recv()
print('Result: {}'.format(result))
ws.close()

I running above method for websocket connection . i got below error .let me know how to solve

Traceback (most recent call last):
  File "C:/Users/Suresh-PC/Downloads/CMC Workbench/robotframework/utils/loginAPI.py", line 11, in <module>
    ws = create_connection('wss://cloud-stg.xyz.com/sockjs/8/****/websocket)
  File "C:\Users\Suresh-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\websocket\_core.py", line 515, in create_connection
    websock.connect(url, **options)
  File "C:\Users\Suresh-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\websocket\_core.py", line 223, in connect
    options.pop('socket', None))
  File "C:\Users\Suresh-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\websocket\_http.py", line 121, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "C:\Users\Suresh-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\websocket\_http.py", line 193, in _open_socket
    raise error
  File "C:\Users\Suresh-PC\AppData\Local\Programs\Python\Python36\lib\site-packages\websocket\_http.py", line 176, in _open_socket
    sock.connect(address)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to the tracker for the project in question instead.
