### ISSUE TITLE
Error in import fbprophet

### ISSUE THREAD

**Issue by MuskanNaaz** [pypa/warehouse#8135]
Collecting fbprophet
  Using cached fbprophet-0.6.tar.gz (54 kB)
Requirement already satisfied: Cython>=0.22 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (0.29.20)
Requirement already satisfied: cmdstanpy==0.4 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (0.4.0)
Requirement already satisfied: pystan>=2.14 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (2.19.1.1)
Requirement already satisfied: numpy>=1.10.0 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (1.18.5)
Requirement already satisfied: pandas>=0.23.4 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (1.0.4)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (3.2.1)
Requirement already satisfied: LunarCalendar>=0.0.9 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (0.0.9)
Requirement already satisfied: convertdate>=2.1.2 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (2.2.1)
Requirement already satisfied: holidays>=0.9.5 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (0.10.2)
Requirement already satisfied: setuptools-git>=1.2 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (1.2)
Requirement already satisfied: python-dateutil>=2.8.0 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from fbprophet) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from pandas>=0.23.4->fbprophet) (2020.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from matplotlib>=2.0.0->fbprophet) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from matplotlib>=2.0.0->fbprophet) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from matplotlib>=2.0.0->fbprophet) (0.10.0)
Requirement already satisfied: ephem>=3.7.5.3 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from LunarCalendar>=0.0.9->fbprophet) (3.7.7.1)
Requirement already satisfied: pymeeus<=1,>=0.3.6 in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from convertdate>=2.1.2->fbprophet) (0.3.7)
Requirement already satisfied: six in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from holidays>=0.9.5->fbprophet) (1.11.0)
Requirement already satisfied: korean_lunar_calendar in c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages (from holidays>=0.9.5->fbprophet) (0.2.1)
Building wheels for collected packages: fbprophet
  Building wheel for fbprophet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\dell\appdata\local\programs\python\python36-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-okhp48e5\\fbprophet\\setup.py'"'"'; __file__='"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-okhp48e5\\fbprophet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\DELL\AppData\Local\Temp\pip-wheel-30yw0zlg'
       cwd: C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\
  Complete output (58 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\fbprophet
  creating build\lib\fbprophet\stan_model
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\setup.py", line 148, in <module>
      """
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\setup.py", line 48, in run
      build_models(target_dir)
    File "C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\setup.py", line 36, in build_models
      from fbprophet.models import StanBackendEnum
    File "C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\fbprophet\__init__.py", line 8, in <module>
      from fbprophet.forecaster import Prophet
    File "C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\fbprophet\forecaster.py", line 15, in <module>
      import pandas as pd
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\__init__.py", line 55, in <module>
      from pandas.core.api import (
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\api.py", line 29, in <module>
      from pandas.core.groupby import Grouper, NamedAgg
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
      from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\groupby\generic.py", line 60, in <module>
      from pandas.core.frame import DataFrame
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\frame.py", line 124, in <module>
      from pandas.core.series import Series
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\series.py", line 4572, in <module>
      Series._add_series_or_dataframe_operations()
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\generic.py", line 10349, in _add_series_or_dataframe_operations
      from pandas.core.window import EWM, Expanding, Rolling, Window
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\window\__init__.py", line 1, in <module>
      from pandas.core.window.ewm import EWM  # noqa:F401
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\window\ewm.py", line 5, in <module>
      import pandas._libs.window.aggregations as window_aggregations
  ImportError: DLL load failed: %1 is not a valid Win32 application.
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
Failed to build fbprophet
Installing collected packages: fbprophet
    Running setup.py install for fbprophet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\dell\appdata\local\programs\python\python36-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-okhp48e5\\fbprophet\\setup.py'"'"'; __file__='"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-okhp48e5\\fbprophet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DELL\AppData\Local\Temp\pip-record-o3ko60ho\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dell\appdata\local\programs\python\python36-32\Include\fbprophet'
         cwd: C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\
    Complete output (60 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\fbprophet
    creating build\lib\fbprophet\stan_model
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\setup.py", line 148, in <module>
        """
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\setup.py", line 48, in run
        build_models(target_dir)
      File "C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\setup.py", line 36, in build_models
        from fbprophet.models import StanBackendEnum
      File "C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\fbprophet\__init__.py", line 8, in <module>
        from fbprophet.forecaster import Prophet
      File "C:\Users\DELL\AppData\Local\Temp\pip-install-okhp48e5\fbprophet\fbprophet\forecaster.py", line 15, in <module>
        import pandas as pd
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\__init__.py", line 55, in <module>
        from pandas.core.api import (
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\api.py", line 29, in <module>
        from pandas.core.groupby import Grouper, NamedAgg
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
        from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\groupby\generic.py", line 60, in <module>
        from pandas.core.frame import DataFrame
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\frame.py", line 124, in <module>
        from pandas.core.series import Series
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\series.py", line 4572, in <module>
        Series._add_series_or_dataframe_operations()
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\generic.py", line 10349, in _add_series_or_dataframe_operations
        from pandas.core.window import EWM, Expanding, Rolling, Window
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\window\__init__.py", line 1, in <module>
        from pandas.core.window.ewm import EWM  # noqa:F401
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\window\ewm.py", line 5, in <module>
        import pandas._libs.window.aggregations as window_aggregations
    ImportError: DLL load failed: %1 is not a valid Win32 application.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\dell\appdata\local\programs\python\python36-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-okhp48e5\\fbprophet\\setup.py'"'"'; __file__='"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-okhp48e5\\fbprophet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DELL\AppData\Local\Temp\pip-record-o3ko60ho\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dell\appdata\local\programs\python\python36-32\Include\fbprophet' Check the logs for full command output.

**Describe the bug**

**Expected behavior**

**To Reproduce**

**My Platform**

**Additional context**

**Comment by di** [comment]
Hi, this issue tracker is for issues with the codebase behind https://pypi.org itself, not the projects hosted on PyPI.

You should report this issue to [the tracker for the project in question instead](https://github.com/facebook/prophet/issues).
